/*
 * list_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `list.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "segal.h"


/*
 * Notify callback function for `but_recall'.
 */
void
list_pop_list_but_recall_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	list_pop_list_objects *ip = (list_pop_list_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		recall_list();
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_store'.
 */
void
list_pop_list_but_store_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	list_pop_list_objects *ip = (list_pop_list_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		store_list();
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_load'.
 */
void
list_pop_list_but_load_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	list_pop_list_objects *ip = (list_pop_list_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		load_list();
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_close'.
 */
void
list_pop_list_but_close_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	list_pop_list_objects *ip = (list_pop_list_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(List_pop_list->pop_list, FRAME_CMD_PUSHPIN_IN, FALSE, NULL);
	xv_set(List_pop_list->pop_list, XV_SHOW, FALSE, NULL);
	
	/* gxv_end_connections */

}
