/*
 * mask_grow_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `mask_grow.G'.
 */

#include "common.h"
#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "segal.h"

/*
 * Notify callback function for `grow_threshold_high'.
 */
void
set_grow_threshold_high(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `grow_threshold_low'.
 */
void
set_grow_threshold_low(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_max_gradient'.
 */
void
set_grow_gradient(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_region'.
 */
void
draw_hints_grow_region(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Event callback function for `but_stop'.
 */
void
grow_stop_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

	panel_default_handle_event(item, event);
}

/*
 * Notify callback function for `but_options'.
 */
void
mask_grow_pop_mask_grow_but_options_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Mask_grow_pop_options->pop_options, FRAME_CMD_PUSHPIN_IN, TRUE, NULL);
	xv_set(Mask_grow_pop_options->pop_options, XV_SHOW, TRUE, NULL);
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_close_grow'.
 */
void
mask_grow_pop_mask_grow_but_close_grow_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Mask_grow_pop_mask_grow->pop_mask_grow, FRAME_CMD_PUSHPIN_IN, FALSE, NULL);
	xv_set(Mask_grow_pop_mask_grow->pop_mask_grow, XV_SHOW, FALSE, NULL);
	
	{
		if(!grow.stack_empty) redisplay_all();
	}
	
	xv_set(Mask_grow_pop_options->pop_options, FRAME_CMD_PUSHPIN_IN, FALSE, NULL);
	xv_set(Mask_grow_pop_options->pop_options, XV_SHOW, FALSE, NULL);
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_close_options'.
 */
void
mask_grow_pop_options_but_close_options_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Mask_grow_pop_options->pop_options, FRAME_CMD_PUSHPIN_IN, FALSE, NULL);
	xv_set(Mask_grow_pop_options->pop_options, XV_SHOW, FALSE, NULL);
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_region'.
 */
void
mask_grow_pop_mask_grow_set_region_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Event callback function for `but_stop'.
 */
void
mask_grow_pop_mask_grow_but_stop_event_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

	panel_default_handle_event(item, event);
}

/*
 * Notify callback function for `set_seed_points_source'.
 */
void
mask_grow_pop_options_set_seed_points_source_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 2)
	{
		grow.seed_pt_src = SEED_ROI;
	}
	
	if (value == 0)
	{
		grow.seed_pt_src = SEED_EDIT;
	}
	
	if (value == 1)
	{
		grow.seed_pt_src = SEED_PTS;
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_3d_extent'.
 */
void
mask_grow_pop_options_set_3d_extent_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_starting_window'.
 */
void
mask_grow_pop_options_set_starting_window_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 0)
	{
		grow.swin = WIN_PAINT;
	}
	
	if (value == 1)
	{
		grow.swin = WIN_VX;
	}
	
	if (value == 2)
	{
		grow.swin = WIN_VY;
	}
	
	if (value == 3)
	{
		grow.swin = WIN_VZ;
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_matrix_type'.
 */
void
mask_grow_pop_options_set_matrix_type_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_matrix_size'.
 */
void
mask_grow_pop_options_set_matrix_size_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_overwrite'.
 */
void
mask_grow_pop_options_set_overwrite_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 0)
	{
		grow.overwrite = TRUE;
	}
	
	if (value == 1)
	{
		grow.overwrite = FALSE;
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_display_growth'.
 */
void
mask_grow_pop_options_set_display_growth_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 0)
	{
		grow.disp_growth = DISP_ALL;
	}
	
	if (value == 1)
	{
		grow.disp_growth = DISP_GROW;
	}
	
	if (value == 2)
	{
		grow.disp_growth = DISP_WHEN_DONE;
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_grow_mask'.
 */
void
mask_grow_pop_mask_grow_but_grow_mask_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `grow_threshold_high'.
 */
void
mask_grow_pop_mask_grow_grow_threshold_high_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `grow_threshold_low'.
 */
void
mask_grow_pop_mask_grow_grow_threshold_low_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_max_gradient'.
 */
void
mask_grow_pop_mask_grow_set_max_gradient_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_apply_threshold_values'.
 */
void
mask_grow_pop_mask_grow_set_apply_threshold_values_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	for (i = 0; i < 1; i++) {
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `set_apply_max_gradient'.
 */
void
mask_grow_pop_mask_grow_set_apply_max_gradient_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	for (i = 0; i < 1; i++) {
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `beg_frame'.
 */
Panel_setting
mask_grow_pop_mask_grow_beg_frame_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	int	value = (int) xv_get(item, PANEL_VALUE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		region.beg_frame = value;
		region.end_frame = value;
		xv_set(Mask_grow_pop_mask_grow->end_frame,
			PANEL_VALUE, value,
			NULL);
	}
	
	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `end_frame'.
 */
Panel_setting
mask_grow_pop_mask_grow_end_frame_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	int	value = (int) xv_get(item, PANEL_VALUE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		region.end_frame = value;
	}
	
	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `but_defaults'.
 */
void
mask_grow_pop_options_but_defaults_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_shrink_mask'.
 */
void
mask_grow_pop_mask_grow_but_shrink_mask_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_apply_min_bridge'.
 */
void
mask_grow_pop_mask_grow_set_apply_min_bridge_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	for (i = 0; i < 1; i++) {
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `set_bridge_type'.
 */
void
mask_grow_pop_options_set_bridge_type_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_bridge_strength'.
 */
void
mask_grow_pop_options_set_bridge_strength_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_min_bridge'.
 */
void
mask_grow_pop_mask_grow_set_min_bridge_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_grow'.
 */
void
mask_grow_pop_mask_grow_but_grow_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.direction = DIR_GROW;
		grow_mask();
	}
	
	xv_set(Mask_grow_pop_mask_grow->but_stop, PANEL_INACTIVE, FALSE, NULL);
	
	xv_set(Mask_grow_pop_mask_grow->but_continue, PANEL_INACTIVE, TRUE, NULL);
	
	xv_set(Mask_grow_pop_mask_grow->but_undo, PANEL_INACTIVE, FALSE, NULL);
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_shrink'.
 */
void
mask_grow_pop_mask_grow_but_shrink_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.direction = DIR_SHRINK;
		grow_mask();
	}
	
	xv_set(Mask_grow_pop_mask_grow->but_stop, PANEL_INACTIVE, FALSE, NULL);
	
	xv_set(Mask_grow_pop_mask_grow->but_continue, PANEL_INACTIVE, TRUE, NULL);
	
	xv_set(Mask_grow_pop_mask_grow->but_undo, PANEL_INACTIVE, FALSE, NULL);
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_stop'.
 */
void
mask_grow_pop_mask_grow_but_stop_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Mask_grow_pop_mask_grow->but_stop, PANEL_INACTIVE, TRUE, NULL);
	
	{
		notify_set_itimer_func(Mask_grow_pop_mask_grow->pop_mask_grow,
			NOTIFY_FUNC_NULL, ITIMER_REAL, NULL, NULL);
	}
	
	xv_set(Mask_grow_pop_mask_grow->but_continue, PANEL_INACTIVE, FALSE, NULL);
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_continue'.
 */
void
mask_grow_pop_mask_grow_but_continue_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	Notify_value grow_edges();

	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Mask_grow_pop_mask_grow->but_stop, PANEL_INACTIVE, FALSE, NULL);
	
	xv_set(Mask_grow_pop_mask_grow->but_continue, PANEL_INACTIVE, TRUE, NULL);
	
	{
		go_grow_edges();
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_delay_useconds'.
 */
void
mask_grow_pop_options_set_delay_useconds_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_speed'.
 */
void
mask_grow_pop_options_set_speed_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_growth_speed'.
 */
void
mask_grow_pop_options_set_growth_speed_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.speed = value;
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_undo'.
 */
void
mask_grow_pop_mask_grow_but_undo_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Mask_grow_pop_mask_grow->but_stop, PANEL_INACTIVE, TRUE, NULL);
	
	xv_set(Mask_grow_pop_mask_grow->but_continue, PANEL_INACTIVE, TRUE, NULL);
	
	xv_set(Mask_grow_pop_mask_grow->but_undo, PANEL_INACTIVE, TRUE, NULL);
	
	{
		if(grow.extent == GROW_FRAME) load_mask_undo_2d(grow.swin);
		else load_mask_undo_3d(segal.e_m);
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_apply_threshold'.
 */
void
mask_grow_pop_mask_grow_set_apply_threshold_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	for (i = 0; i < 1; i++) {
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			if(grow.apply_thresholds) {
				grow.apply_thresholds = FALSE;
				xv_set(Mask_grow_pop_mask_grow->set_threshold_max,
					PANEL_INACTIVE, TRUE,
					NULL);
				xv_set(Mask_grow_pop_mask_grow->set_threshold_min,
					PANEL_INACTIVE, TRUE,
					NULL);
			}
			else {
				grow.apply_thresholds = TRUE;
				xv_set(Mask_grow_pop_mask_grow->set_threshold_max,
					PANEL_INACTIVE, FALSE,
					NULL);
				xv_set(Mask_grow_pop_mask_grow->set_threshold_min,
					PANEL_INACTIVE, FALSE,
					NULL);
			}
		}
		
		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `grow_threshold_max'.
 */
void
mask_grow_pop_mask_grow_grow_threshold_max_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `grow_threshold_min'.
 */
void
mask_grow_pop_mask_grow_grow_threshold_min_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_apply_gradient'.
 */
void
mask_grow_pop_mask_grow_set_apply_gradient_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	for (i = 0; i < 1; i++) {
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			if(grow.apply_gradient) {
				grow.apply_gradient = FALSE;
				xv_set(Mask_grow_pop_mask_grow->set_gradient_radius,
					PANEL_INACTIVE, TRUE,
					NULL);
				xv_set(Mask_grow_pop_mask_grow->set_gradient_max,
					PANEL_INACTIVE, TRUE,
					NULL);
				xv_set(Mask_grow_pop_mask_grow->set_gradient_min,
					PANEL_INACTIVE, TRUE,
					NULL);
			}
			else {
				grow.apply_gradient = TRUE;
				xv_set(Mask_grow_pop_mask_grow->set_gradient_radius,
					PANEL_INACTIVE, FALSE,
					NULL);
				xv_set(Mask_grow_pop_mask_grow->set_gradient_max,
					PANEL_INACTIVE, FALSE,
					NULL);
				xv_set(Mask_grow_pop_mask_grow->set_gradient_min,
					PANEL_INACTIVE, FALSE,
					NULL);
			}
		}
		
		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `set_gradient_radius'.
 */
void
mask_grow_pop_mask_grow_set_gradient_radius_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.gradient_rad = value;
		
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_gradient_max'.
 */
void
mask_grow_pop_mask_grow_set_gradient_max_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.gradient_max = value;
		if(value < grow.gradient_min) {
			grow.gradient_min = value;
			xv_set(Mask_grow_pop_mask_grow->set_gradient_min,
				PANEL_VALUE, value,
				NULL);
		}
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_gradient_min'.
 */
void
mask_grow_pop_mask_grow_set_gradient_min_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.gradient_min = value;
		if(value > grow.gradient_max) {
			grow.gradient_max = value;
			xv_set(Mask_grow_pop_mask_grow->set_gradient_max,
				PANEL_VALUE, value,
				NULL);
		}
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_apply_bridge'.
 */
void
mask_grow_pop_mask_grow_set_apply_bridge_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	for (i = 0; i < 1; i++) {
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			if(grow.apply_bridge) {
				grow.apply_bridge = FALSE;
				xv_set(Mask_grow_pop_mask_grow->set_bridge_distance,
					PANEL_INACTIVE, TRUE,
					NULL);
				xv_set(Mask_grow_pop_mask_grow->set_bridge_max,
					PANEL_INACTIVE, TRUE,
					NULL);
				xv_set(Mask_grow_pop_mask_grow->set_bridge_min,
					PANEL_INACTIVE, TRUE,
					NULL);
			}
			else {
				grow.apply_bridge = TRUE;
				xv_set(Mask_grow_pop_mask_grow->set_bridge_distance,
					PANEL_INACTIVE, FALSE,
					NULL);
				xv_set(Mask_grow_pop_mask_grow->set_bridge_max,
					PANEL_INACTIVE, FALSE,
					NULL);
				xv_set(Mask_grow_pop_mask_grow->set_bridge_min,
					PANEL_INACTIVE, FALSE,
					NULL);
			}
		}
		
		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `set_bridge_distance'.
 */
void
mask_grow_pop_mask_grow_set_bridge_distance_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.bridge_dist = value;
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_bridge_max'.
 */
void
mask_grow_pop_mask_grow_set_bridge_max_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.bridge_max = value;
		if(value < grow.bridge_min) {
			grow.bridge_min = value;
			xv_set(Mask_grow_pop_mask_grow->set_bridge_min,
				PANEL_VALUE, value,
				NULL);
		}
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_bridge_min'.
 */
void
mask_grow_pop_mask_grow_set_bridge_min_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.bridge_min = value;
		if(value > grow.bridge_max) {
			grow.bridge_max = value;
			xv_set(Mask_grow_pop_mask_grow->set_bridge_max,
				PANEL_VALUE, value,
				NULL);
		}
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_extent'.
 */
void
mask_grow_pop_mask_grow_set_extent_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 2)
	{
		grow.extent = GROW_ALL;
	}
	
	if (value == 1)
	{
		xv_set(Mask_grow_pop_mask_grow->beg_frame, PANEL_INACTIVE, FALSE, NULL);
	}
	
	if (value == 0)
	{
		xv_set(Mask_grow_pop_mask_grow->beg_frame, PANEL_INACTIVE, TRUE, NULL);
	}
	
	if (value == 2)
	{
		xv_set(Mask_grow_pop_mask_grow->beg_frame, PANEL_INACTIVE, TRUE, NULL);
	}
	
	if (value == 1)
	{
		xv_set(Mask_grow_pop_mask_grow->end_frame, PANEL_INACTIVE, FALSE, NULL);
	}
	
	if (value == 0)
	{
		xv_set(Mask_grow_pop_mask_grow->end_frame, PANEL_INACTIVE, TRUE, NULL);
	}
	
	if (value == 2)
	{
		xv_set(Mask_grow_pop_mask_grow->end_frame, PANEL_INACTIVE, TRUE, NULL);
	}
	
	if (value == 0)
	{
		grow.extent = GROW_FRAME;
	}
	
	if (value == 1)
	{
		grow.extent = GROW_BEG_TO_END;
		region.beg_frame = win[grow.swin].f;
		region.end_frame = win[grow.swin].f;
		xv_set(Mask_grow_pop_mask_grow->beg_frame,
			PANEL_VALUE, region.beg_frame,
			NULL);
		xv_set(Mask_grow_pop_mask_grow->end_frame,
			PANEL_VALUE, region.end_frame,
			NULL);
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_defaults_grow'.
 */
void
mask_grow_pop_mask_grow_but_defaults_grow_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_defaults_options'.
 */
void
mask_grow_pop_options_but_defaults_options_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.swin = WIN_PAINT;
		grow.seed_pt_src = SEED_EDIT;
		grow.overwrite = TRUE;
		grow.disp_growth = DISP_ALL;
		grow.speed = 2000;
		
		/* reset ui fields */
		xv_set(Mask_grow_pop_options->set_starting_window,
			PANEL_VALUE, grow.swin,
			NULL);
		xv_set(Mask_grow_pop_options->set_seed_points_source,
			PANEL_VALUE, grow.seed_pt_src,
			NULL);
		xv_set(Mask_grow_pop_options->set_overwrite,
			PANEL_VALUE, grow.overwrite,
			NULL);
		xv_set(Mask_grow_pop_options->set_display_growth,
			PANEL_VALUE, grow.disp_growth,
			NULL);
		xv_set(Mask_grow_pop_options->set_growth_speed,
			PANEL_VALUE, grow.speed,
			NULL);
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_threshold_max'.
 */
void
mask_grow_pop_mask_grow_set_threshold_max_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.threshold_max = value;
		if(value < grow.threshold_min) {
			grow.threshold_min = value;
			xv_set(Mask_grow_pop_mask_grow->set_threshold_min,
				PANEL_VALUE, value,
				NULL);
		}
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_threshold_min'.
 */
void
mask_grow_pop_mask_grow_set_threshold_min_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_mask_grow_objects *ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		grow.threshold_min = value;
		if(value > grow.threshold_max) {
			grow.threshold_max = value;
			xv_set(Mask_grow_pop_mask_grow->set_threshold_max,
				PANEL_VALUE, value,
				NULL);
		}
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_grow_interractive'.
 */
void
mask_grow_pop_options_set_grow_interractive_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	mask_grow_pop_options_objects *ip = (mask_grow_pop_options_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 1)
	{
		grow.interractive = FALSE;
	}
	
	if (value == 0)
	{
		grow.interractive = TRUE;
	}
	
	/* gxv_end_connections */

}

/*
 * Menu handler for `menu_set_grow_parameters (Default)'.
 */
Menu_item
mask_grow_menu_set_grow_parameters_item0_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	mask_grow_pop_mask_grow_objects * ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			if(grow.apply_thresholds) {
				grow.threshold_min = 0;
				grow.threshold_max = 255;
			}
			if(grow.apply_gradient) {
				grow.gradient_rad = 1;
				grow.gradient_min = 0;
				grow.gradient_max = 100;
			}
			if(grow.apply_bridge) {
				grow.bridge_dist = 5;
				grow.bridge_min = 1;
				grow.bridge_max = 8;
			}
			
			/* reset ui fields */
			set_grow_params();
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_set_grow_parameters (From edit mask)'.
 */
Menu_item
mask_grow_menu_set_grow_parameters_item1_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	mask_grow_pop_mask_grow_objects * ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			auto_set_grow_params(SEED_EDIT);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_set_grow_parameters (From point list)'.
 */
Menu_item
mask_grow_menu_set_grow_parameters_item2_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	mask_grow_pop_mask_grow_objects * ip = (mask_grow_pop_mask_grow_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			auto_set_grow_params(SEED_PTS);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}
