/*
 * paint_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `paint.G'.
 */

#include "common.h"
#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "segal.h"

/*
 * Menu handler for `menu_brush_mode (Mask)'.
 */
Menu_item
paint_menu_brush_mode_item0_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_mode (Image)'.
 */
Menu_item
paint_menu_brush_mode_item1_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_mask (Paint)'.
 */
Menu_item
paint_menu_brush_affect_mask_item0_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_mask (Erase)'.
 */
Menu_item
paint_menu_brush_affect_mask_item1_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_image_lighter (5)'.
 */
Menu_item
paint_menu_brush_affect_image_lighter_item0_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_image_lighter (10)'.
 */
Menu_item
paint_menu_brush_affect_image_lighter_item1_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_image_lighter (20)'.
 */
Menu_item
paint_menu_brush_affect_image_lighter_item2_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_image_lighter (50)'.
 */
Menu_item
paint_menu_brush_affect_image_lighter_item3_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_image_lighter (100)'.
 */
Menu_item
paint_menu_brush_affect_image_lighter_item4_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_image_darker (5)'.
 */
Menu_item
paint_menu_brush_affect_image_darker_item0_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_image_darker (10)'.
 */
Menu_item
paint_menu_brush_affect_image_darker_item1_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_image_darker (20)'.
 */
Menu_item
paint_menu_brush_affect_image_darker_item2_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_image_darker (50)'.
 */
Menu_item
paint_menu_brush_affect_image_darker_item3_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_affect_image_darker (100)'.
 */
Menu_item
paint_menu_brush_affect_image_darker_item4_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_shape (Square)'.
 */
Menu_item
paint_menu_brush_shape_item0_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_shape (Round)'.
 */
Menu_item
paint_menu_brush_shape_item1_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_size (1 x 1)'.
 */
Menu_item
paint_menu_brush_size_item0_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_size (2 x 2)'.
 */
Menu_item
paint_menu_brush_size_item1_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_size (3 x 3)'.
 */
Menu_item
paint_menu_brush_size_item2_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_size (4 x 4)'.
 */
Menu_item
paint_menu_brush_size_item3_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_size (5 x 5)'.
 */
Menu_item
paint_menu_brush_size_item4_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_size (10 x 10)'.
 */
Menu_item
paint_menu_brush_size_item5_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_brush_size (20 x 20)'.
 */
Menu_item
paint_menu_brush_size_item6_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_mask (Cut)'.
 */
Menu_item
paint_menu_edit_mask_item0_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			copy_mask(win[WIN_PAINT].m_data[0], bm,
				m[segal.e_m].bit_key, bm_key[win[WIN_PAINT].aspect + 3],
				win[WIN_PAINT].img_size);
			fill_mask(R2d_WHOLE, WIN_PAINT, BLACK);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_mask (Copy)'.
 */
Menu_item
paint_menu_edit_mask_item1_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			copy_mask(win[WIN_PAINT].m_data[0], bm,
				m[segal.e_m].bit_key, bm_key[win[WIN_PAINT].aspect + 3],
				win[WIN_PAINT].img_size);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_mask (Paste)'.
 */
Menu_item
paint_menu_edit_mask_item2_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			copy_mask(bm, win[WIN_PAINT].m_data[0],
				bm_key[win[WIN_PAINT].aspect + 3], m[segal.e_m].bit_key,
				win[WIN_PAINT].img_size);
			m[segal.e_m].changed_frame = TRUE;
			save_mask_frame(WIN_PAINT);
			redisplay_paint();
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_mask (Undo)'.
 */
Menu_item
paint_menu_edit_mask_item3_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			load_mask_undo_2d(WIN_PAINT);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_mask (Clear frame)'.
 */
Menu_item
paint_menu_edit_mask_item6_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			fill_mask(R2d_WHOLE, WIN_PAINT, BLACK);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_mask (Clear whole mask)'.
 */
Menu_item
paint_menu_edit_mask_item7_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			fill_mask(R3d_WHOLE, WIN_PAINT, BLACK);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_mask (Fill frame)'.
 */
Menu_item
paint_menu_edit_mask_item8_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			fill_mask(R2d_WHOLE, WIN_PAINT, WHITE);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_mask (Fill whole mask)'.
 */
Menu_item
paint_menu_edit_mask_item9_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			fill_mask(R3d_WHOLE, WIN_PAINT, WHITE);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_mask (Invert frame)'.
 */
Menu_item
paint_menu_edit_mask_item10_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			fill_mask(R2d_WHOLE, WIN_PAINT, INVERT);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_mask (Invert whole mask)'.
 */
Menu_item
paint_menu_edit_mask_item11_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			fill_mask(R3d_WHOLE, WIN_PAINT, INVERT);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_image (Undo)'.
 */
Menu_item
paint_menu_edit_image_item0_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			load_image_undo(WIN_PAINT);
			redisplay_all();
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_edit_image (Original)'.
 */
Menu_item
paint_menu_edit_image_item1_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			load_image_orig(WIN_PAINT);
			redisplay_all();
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_apply_log (This frame)'.
 */
Menu_item
paint_menu_apply_log_item0_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	paint_win_paint_objects * ip = (paint_win_paint_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			apply_log(R2d_WHOLE);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Menu handler for `menu_apply_log (Whole image)'.
 */
Menu_item
paint_menu_apply_log_item1_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	paint_win_paint_objects * ip = (paint_win_paint_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
			apply_log(R3d_WHOLE);
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Notify callback function for `but_close'.
 */
void
paint_win_paint_but_close_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	paint_win_paint_objects *ip = (paint_win_paint_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_aspect'.
 */
void
paint_win_paint_set_aspect_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	paint_win_paint_objects *ip = (paint_win_paint_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		win[WIN_PAINT].aspect = value;
		win[WIN_PAINT].f = win[value].f;
		paint_setup();
		realloc_window_buffers(WIN_PAINT);
		realloc_window_ximage(WIN_PAINT);
		redisplay_paint();
		
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_zoom_mag'.
 */
void
paint_win_paint_set_zoom_mag_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	paint_win_paint_objects *ip = (paint_win_paint_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		win[WIN_PAINT].zoom_mag = value + 1;
		paint_setup();
		realloc_window_ximage(WIN_PAINT);
		redisplay_paint();
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_paint_frame'.
 */
void
paint_win_paint_set_paint_frame_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	paint_win_paint_objects *ip = (paint_win_paint_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		win[WIN_PAINT].f = value;
		win[WIN_PAINT].repaint = TRUE;
		redisplay_paint();
		
		save_image_orig(WIN_PAINT);
		
		if(xv_get(Threshold_pop_threshold->pop_threshold,
				XV_SHOW, NULL)
		&& (threshold.roi == R2d_WHOLE
		|| threshold.roi == R2d_CROP
		|| threshold.roi == R2d_PT_LIST)) refresh_histogram();
		
	}
	
	/* gxv_end_connections */

}

/*
 * Event callback function for `canvas'.
 */
Notify_value
paint_win_paint_canvas_event_callback(win, event, arg, type)
	Xv_window	win;
	Event		*event;
	Notify_arg	arg;
	Notify_event_type type;
{
	paint_win_paint_objects *ip = (paint_win_paint_objects *) xv_get(xv_get(win, CANVAS_PAINT_CANVAS_WINDOW), XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		paint_event(event);
	}
	
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * Repaint callback function for `canvas'.
 */
void
paint_win_paint_canvas_repaint_callback(canvas, paint_window, rects)
	Canvas		canvas;
	Xv_window	paint_window;
	Rectlist	*rects;
{
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		win[WIN_PAINT].repaint = TRUE;
		map_buffers();
	}
	
	/* gxv_end_connections */

}

/*
 * Menu handler for `menu_edit_mask (Clear frame)'.
 */
Menu_item
paint_menu_edit_mask_item5_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	Xv_opaque ip = (Xv_opaque) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Notify callback function for `set_affect_mask'.
 */
void
paint_pop_brush_set_affect_mask_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	paint_pop_brush_objects *ip = (paint_pop_brush_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 1)
	{
		brush.mask_affect = MASK_ERASE;
		change_cursor_proc();
	}
	
	if (value == 0)
	{
		brush.mask_affect = MASK_PAINT;
		change_cursor_proc();
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_affect_image'.
 */
void
paint_pop_brush_set_affect_image_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	paint_pop_brush_objects *ip = (paint_pop_brush_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 1)
	{
		brush.image_affect = brush.degree;
		
	}
	
	if (value == 0)
	{
		brush.image_affect = -1 * brush.degree;
		
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_degree'.
 */
void
paint_pop_brush_set_degree_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	paint_pop_brush_objects *ip = (paint_pop_brush_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 2)
	{
		brush.degree = 10;
		
	}
	
	if (value == 5)
	{
		brush.degree = 100;
		
	}
	
	if (value == 0)
	{
		brush.degree = 2;
		
	}
	
	if (value == 3)
	{
		brush.degree = 20;
		
	}
	
	if (value == 1)
	{
		brush.degree = 5;
		
	}
	
	if (value == 4)
	{
		brush.degree = 50;
		
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_shape'.
 */
void
paint_pop_brush_set_shape_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	paint_pop_brush_objects *ip = (paint_pop_brush_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 1)
	{
		brush.shape = BRUSH_ROUND;
		change_cursor_proc();
	}
	
	if (value == 0)
	{
		brush.shape = BRUSH_SQUARE;
		change_cursor_proc();
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_size'.
 */
void
paint_pop_brush_set_size_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	paint_pop_brush_objects *ip = (paint_pop_brush_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		brush.size = value;
		change_cursor_proc();
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_close'.
 */
void
paint_pop_brush_but_close_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	paint_pop_brush_objects *ip = (paint_pop_brush_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Paint_pop_brush->pop_brush, FRAME_CMD_PUSHPIN_IN, FALSE, NULL);
	xv_set(Paint_pop_brush->pop_brush, XV_SHOW, FALSE, NULL);
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_brush'.
 */
void
paint_win_paint_but_brush_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	paint_win_paint_objects *ip = (paint_win_paint_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Paint_pop_brush->pop_brush, FRAME_CMD_PUSHPIN_IN, TRUE, NULL);
	xv_set(Paint_pop_brush->pop_brush, XV_SHOW, TRUE, NULL);
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_mode'.
 */
void
paint_pop_brush_set_mode_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	paint_pop_brush_objects *ip = (paint_pop_brush_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 0)
	{
		brush.mode = BRUSH_MASK;
		xv_set(Paint_pop_brush->set_affect_image,
			XV_SHOW, FALSE,
			NULL);
		xv_set(Paint_pop_brush->set_degree,
			XV_SHOW, FALSE,
			NULL);
		xv_set(Paint_pop_brush->set_affect_mask,
			XV_SHOW, TRUE,
			NULL);
	}
	
	if (value == 1)
	{
		brush.mode = BRUSH_IMAGE;
		xv_set(Paint_pop_brush->set_affect_mask,
			XV_SHOW, FALSE,
			NULL);
		xv_set(Paint_pop_brush->set_affect_image,
			XV_SHOW, TRUE,
			NULL);
		xv_set(Paint_pop_brush->set_degree,
			XV_SHOW, TRUE,
			NULL);
		
	}
	
	if (value == 2)
	{
		brush.mode = BRUSH_PTS;
		xv_set(Paint_pop_brush->set_affect_image,
			XV_SHOW, FALSE,
			NULL);
		xv_set(Paint_pop_brush->set_degree,
			XV_SHOW, FALSE,
			NULL);
		xv_set(Paint_pop_brush->set_affect_mask,
			XV_SHOW, TRUE,
			NULL);
	}
	
	/* gxv_end_connections */

}
