/*
 * preferences_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `preferences.G'.
 */

#include "common.h"
#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "segal.h"

/*
 * Notify callback function for `set_image_contrast'.
 */
void
change_colormap(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	preferences_pop_preferences_display_objects *ip = (preferences_pop_preferences_display_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_image_opacity'.
 */
void
slider_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	preferences_pop_preferences_display_objects *ip = (preferences_pop_preferences_display_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_close'.
 */
void
preferences_pop_preferences_display_but_close_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	preferences_pop_preferences_display_objects *ip = (preferences_pop_preferences_display_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Preferences_pop_preferences_display->pop_preferences_display, FRAME_CMD_PUSHPIN_IN, FALSE, NULL);
	xv_set(Preferences_pop_preferences_display->pop_preferences_display, XV_SHOW, FALSE, NULL);
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_image_contrast'.
 */
void
preferences_pop_preferences_display_set_image_contrast_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	preferences_pop_preferences_display_objects *ip = (preferences_pop_preferences_display_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		cmap_init();
		build_cmap();
		redisplay_all();
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_image_opacity'.
 */
void
preferences_pop_preferences_display_set_image_opacity_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	preferences_pop_preferences_display_objects *ip = (preferences_pop_preferences_display_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		cmap_init();
		build_cmap();
		redisplay_all();
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_mask_opacity'.
 */
void
preferences_pop_preferences_display_set_mask_opacity_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	preferences_pop_preferences_display_objects *ip = (preferences_pop_preferences_display_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		cmap_init();
		build_cmap();
		redisplay_all();
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_requant_win'.
 */
void
preferences_pop_preferences_display_set_requant_win_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	preferences_pop_preferences_display_objects *ip = (preferences_pop_preferences_display_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 3)
	{
		rgb.quant.win = WIN_PAINT;
	}
	
	if (value == 0)
	{
		rgb.quant.win = WIN_VX;
	}
	
	if (value == 1)
	{
		rgb.quant.win = WIN_VY;
	}
	
	if (value == 2)
	{
		rgb.quant.win = WIN_VZ;
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `set_requant_quality'.
 */
void
preferences_pop_preferences_display_set_requant_quality_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	preferences_pop_preferences_display_objects *ip = (preferences_pop_preferences_display_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 0)
	{
		rgb.quant.quality = Q_BEST;
	}
	
	if (value == 1)
	{
		rgb.quant.quality = Q_MEDIUM;
	}
	
	if (value == 2)
	{
		rgb.quant.quality = Q_WORST;
	}
	
	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_requant'.
 */
void
preferences_pop_preferences_display_but_requant_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	preferences_pop_preferences_display_objects *ip = (preferences_pop_preferences_display_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		quantize();
	}
	
	/* gxv_end_connections */

}
