/*
 * file_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `file.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "file_ui.h"
#include "gen.h"
#include "genial.h"


/*
 * Global object definitions.
 */
file_window1_objects	*File_window1;
file_rect_choice_win_objects	*File_rect_choice_win;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(argc, argv)
	int	argc;
	char	**argv;
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	File_window1 = file_window1_objects_initialize(NULL, NULL);
	File_rect_choice_win = file_rect_choice_win_objects_initialize(NULL, File_window1->window1);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(File_window1->window1);
	exit(0);
}

#endif


/*
 * Notify callback function for `lmode'.
 */
void
lmode_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	file_window1_objects *ip = (file_window1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "file: lmode_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `load'.
 */
void
load_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	file_window1_objects *ip = (file_window1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("file: load_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `chooser_load'.
 */
void
chooser_load_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	file_window1_objects *ip = (file_window1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("file: chooser_load_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `l_fname'.
 */
Panel_setting
lname_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	file_window1_objects *ip = (file_window1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "file: lname_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `smode'.
 */
void
smode_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	file_window1_objects *ip = (file_window1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "file: smode_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `save'.
 */
void
save_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	file_window1_objects *ip = (file_window1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("file: save_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `chooser_save'.
 */
void
chooser_save_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	file_window1_objects *ip = (file_window1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("file: chooser_save_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `s_fname'.
 */
Panel_setting
sname_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	file_window1_objects *ip = (file_window1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "file: sname_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `box_lid'.
 */
Panel_setting
boxid_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	file_rect_choice_win_objects *ip = (file_rect_choice_win_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	int	value = (int) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "file: boxid_proc: value: %d\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `box_save'.
 */
void
box_save_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	file_rect_choice_win_objects *ip = (file_rect_choice_win_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("file: box_save_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `box_cancel'.
 */
void
box_cancel_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	file_rect_choice_win_objects *ip = (file_rect_choice_win_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("file: box_cancel_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}
