#ifndef	file_HEADER
#define	file_HEADER

/*
 * file_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `file.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	window1;
	Xv_opaque	controls1;
	Xv_opaque	message1;
	Xv_opaque	lmode;
	Xv_opaque	load;
	Xv_opaque	chooser_load;
	Xv_opaque	l_fname;
	Xv_opaque	message2;
	Xv_opaque	smode;
	Xv_opaque	save;
	Xv_opaque	chooser_save;
	Xv_opaque	s_fname;
} file_window1_objects;

extern file_window1_objects	*file_window1_objects_initialize();

extern Xv_opaque	file_window1_window1_create();
extern Xv_opaque	file_window1_controls1_create();
extern Xv_opaque	file_window1_message1_create();
extern Xv_opaque	file_window1_lmode_create();
extern Xv_opaque	file_window1_load_create();
extern Xv_opaque	file_window1_chooser_load_create();
extern Xv_opaque	file_window1_l_fname_create();
extern Xv_opaque	file_window1_message2_create();
extern Xv_opaque	file_window1_smode_create();
extern Xv_opaque	file_window1_save_create();
extern Xv_opaque	file_window1_chooser_save_create();
extern Xv_opaque	file_window1_s_fname_create();

typedef struct {
	Xv_opaque	rect_choice_win;
	Xv_opaque	controls2;
	Xv_opaque	message3;
	Xv_opaque	box_lid;
	Xv_opaque	box_save;
	Xv_opaque	box_cancel;
} file_rect_choice_win_objects;

extern file_rect_choice_win_objects	*file_rect_choice_win_objects_initialize();

extern Xv_opaque	file_rect_choice_win_rect_choice_win_create();
extern Xv_opaque	file_rect_choice_win_controls2_create();
extern Xv_opaque	file_rect_choice_win_message3_create();
extern Xv_opaque	file_rect_choice_win_box_lid_create();
extern Xv_opaque	file_rect_choice_win_box_save_create();
extern Xv_opaque	file_rect_choice_win_box_cancel_create();
#endif
