#ifndef	main_control_HEADER
#define	main_control_HEADER

/*
 * main_control_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `main_control.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	ctrlwin;
	Xv_opaque	controls1;
	Xv_opaque	message1;
	Xv_opaque	image_fname;
	Xv_opaque	file;
	Xv_opaque	quit;
	Xv_opaque	prev;
	Xv_opaque	next;
	Xv_opaque	frame_stat;
	Xv_opaque	func_sel;
	Xv_opaque	reg_type;
	Xv_opaque	message2;
	Xv_opaque	log_num;
	Xv_opaque	eval;
	Xv_opaque	refresh;
	Xv_opaque	clear;
	Xv_opaque	clear_all;
	Xv_opaque	display;
	Xv_opaque	setting1;
	Xv_opaque	lmode;
	Xv_opaque	controls2;
	Xv_opaque	statmsg1;
	Xv_opaque	statmsg2;
	Xv_opaque	statmsg3;
	Xv_opaque	statmsg4;
	Xv_opaque	controls3;
	Xv_opaque	edit_mode;
	Xv_opaque	edit_ok;
	Xv_opaque	message7;
	Xv_opaque	edit_log_num;
	Xv_opaque	button1;
	Xv_opaque	message9;
	Xv_opaque	controls4;
	Xv_opaque	infomesg;
	Xv_opaque	message3;
	Xv_opaque	xlabel;
	Xv_opaque	message4;
	Xv_opaque	ylabel;
	Xv_opaque	message5;
	Xv_opaque	glabel;
	Xv_opaque	imglabel;
} main_control_ctrlwin_objects;

extern main_control_ctrlwin_objects	*main_control_ctrlwin_objects_initialize();

extern Xv_opaque	main_control_ctrlwin_ctrlwin_create();
extern Xv_opaque	main_control_ctrlwin_controls1_create();
extern Xv_opaque	main_control_ctrlwin_message1_create();
extern Xv_opaque	main_control_ctrlwin_image_fname_create();
extern Xv_opaque	main_control_ctrlwin_file_create();
extern Xv_opaque	main_control_ctrlwin_quit_create();
extern Xv_opaque	main_control_ctrlwin_prev_create();
extern Xv_opaque	main_control_ctrlwin_next_create();
extern Xv_opaque	main_control_ctrlwin_frame_stat_create();
extern Xv_opaque	main_control_ctrlwin_func_sel_create();
extern Xv_opaque	main_control_ctrlwin_reg_type_create();
extern Xv_opaque	main_control_ctrlwin_message2_create();
extern Xv_opaque	main_control_ctrlwin_log_num_create();
extern Xv_opaque	main_control_ctrlwin_eval_create();
extern Xv_opaque	main_control_ctrlwin_refresh_create();
extern Xv_opaque	main_control_ctrlwin_clear_create();
extern Xv_opaque	main_control_ctrlwin_clear_all_create();
extern Xv_opaque	main_control_ctrlwin_display_create();
extern Xv_opaque	main_control_ctrlwin_setting1_create();
extern Xv_opaque	main_control_ctrlwin_lmode_create();
extern Xv_opaque	main_control_ctrlwin_controls2_create();
extern Xv_opaque	main_control_ctrlwin_statmsg1_create();
extern Xv_opaque	main_control_ctrlwin_statmsg2_create();
extern Xv_opaque	main_control_ctrlwin_statmsg3_create();
extern Xv_opaque	main_control_ctrlwin_statmsg4_create();
extern Xv_opaque	main_control_ctrlwin_controls3_create();
extern Xv_opaque	main_control_ctrlwin_edit_mode_create();
extern Xv_opaque	main_control_ctrlwin_edit_ok_create();
extern Xv_opaque	main_control_ctrlwin_message7_create();
extern Xv_opaque	main_control_ctrlwin_edit_log_num_create();
extern Xv_opaque	main_control_ctrlwin_button1_create();
extern Xv_opaque	main_control_ctrlwin_message9_create();
extern Xv_opaque	main_control_ctrlwin_controls4_create();
extern Xv_opaque	main_control_ctrlwin_infomesg_create();
extern Xv_opaque	main_control_ctrlwin_message3_create();
extern Xv_opaque	main_control_ctrlwin_xlabel_create();
extern Xv_opaque	main_control_ctrlwin_message4_create();
extern Xv_opaque	main_control_ctrlwin_ylabel_create();
extern Xv_opaque	main_control_ctrlwin_message5_create();
extern Xv_opaque	main_control_ctrlwin_glabel_create();
extern Xv_opaque	main_control_ctrlwin_imglabel_create();

typedef struct {
	Xv_opaque	imgwin;
	Xv_opaque	imgcanv;
} main_control_imgwin_objects;

extern main_control_imgwin_objects	*main_control_imgwin_objects_initialize();

extern Xv_opaque	main_control_imgwin_imgwin_create();
extern Xv_opaque	main_control_imgwin_imgcanv_create();
#endif
