/*
 * main_control_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `main_control.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "genial.h"
#include "main_control_ui.h"


#ifdef MAIN


#endif

void		imgwin_resize_proc();

/*
 * Global object definitions.
 */
main_control_ctrlwin_objects	*Main_control_ctrlwin;
main_control_imgwin_objects	*Main_control_imgwin;
/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

/*
 * Notify callback function for `quit'.
 */
void
quit_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: quit_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `file'.
 */
void
file_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: file_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `display'.
 */
void
dpyopt_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: dpyopt_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `prev'.
 */
void
prev_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: prev_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `next'.
 */
void
next_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: next_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `func_sel'.
 */
void
func_sel_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "genial: func_sel_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `eval'.
 */
void
eval_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: eval_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `clear'.
 */
void
clear_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: clear_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `clear_all'.
 */
void
clear_all_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: clear_all_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `refresh'.
 */
void
refresh_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: refresh_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `autolog'.
 */
void
autolog_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	fputs("genial: autolog_proc\n", stderr);
	for (i = 0; i < 1; i++) {
		if (value & 01)
			fprintf(stderr, "\t%dth item selected\n", i);
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `options'.
 */
void
opt_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: opt_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `reg_type'.
 */
void
reg_type_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "genial: reg_type_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `edit_mode'.
 */
void
edit_region_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "genial: edit_region_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `lmode'.
 */
void
linemode_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "genial: linemode_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Event callback function for `imgwin'.
 */
Notify_value
main_control_imgwin_event_callback(win, event, arg, type)
	Xv_window	win;
	Event		*event;
	Notify_arg	arg;
	Notify_event_type type;
{
	main_control_imgwin_objects *ip = (main_control_imgwin_objects *) xv_get(win, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "genial: main_control_imgwin_event_callback: event %d\n", event_id(event));
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (event_action(event) == WIN_RESIZE)
	{
		imgwin_resize_proc(win, event, arg, type);
	}
	
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * User-defined action for `imgwin'.
 */
void
imgwin_resize_proc(win, event, arg, type)
	Xv_window	win;
	Event		*event;
	Notify_arg	arg;
	Notify_event_type type;
{
	main_control_imgwin_objects *ip = (main_control_imgwin_objects *) xv_get(win, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "genial: imgwin_resize_proc: event %d\n", event_id(event));
}

/*
 * Event callback function for `imgcanv'.
 */
Notify_value
imgwin_event_proc(win, event, arg, type)
	Xv_window	win;
	Event		*event;
	Notify_arg	arg;
	Notify_event_type type;
{
	main_control_imgwin_objects *ip = (main_control_imgwin_objects *) xv_get(xv_get(win, CANVAS_PAINT_CANVAS_WINDOW), XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "genial: imgwin_event_proc: event %d\n", event_id(event));
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * Repaint callback function for `imgcanv'.
 */
void
imgwin_repaint_proc(canvas, paint_window, display, xid, rects)
	Canvas		canvas;
	Xv_window	paint_window;
	Display		*display;
	Window		xid;
	Xv_xrectlist	*rects;
{
	fputs("genial: imgwin_repaint_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `edit_log_num'.
 */
void
edit_log_num_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "main_control: edit_log_num_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `edit_ok'.
 */
void
do_edit_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: do_edit_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `setting1'.
 */
void
set_clean_mode(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	fputs("main_control: set_clean_mode\n", stderr);
	for (i = 0; i < 0; i++) {
		if (value & 01)
			fprintf(stderr, "\t%dth item selected\n", i);
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `button1'.
 */
void
renumber_logged_objects(item, event)
	Panel_item	item;
	Event		*event;
{
	main_control_ctrlwin_objects *ip = (main_control_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("main_control: renumber_logged_objects\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}
