/*
 * trace_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `trace.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "trace_ui.h"
#include <group.h>
#include "gen.h"
#include "genial.h"


/*
 * Global object definitions.
 */
trace_tcntrl_objects	*Trace_tcntrl;
trace_trwin_objects	*Trace_trwin;
trace_intgwin_objects	*Trace_intgwin;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(argc, argv)
	int	argc;
	char	**argv;
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Trace_tcntrl = trace_tcntrl_objects_initialize(NULL, NULL);
	Trace_trwin = trace_trwin_objects_initialize(NULL, NULL);
	Trace_intgwin = trace_intgwin_objects_initialize(NULL, NULL);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Trace_tcntrl->tcntrl);
	exit(0);
}

#endif


/*
 * Notify callback function for `traceno'.
 */
Panel_setting
traceno_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	trace_tcntrl_objects *ip = (trace_tcntrl_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	int	value = (int) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "trace: traceno_proc: value: %d\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `radius'.
 */
Panel_setting
rad_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	trace_tcntrl_objects *ip = (trace_tcntrl_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	int	value = (int) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "trace: rad_proc: value: %d\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `scale'.
 */
void
scale_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	trace_tcntrl_objects *ip = (trace_tcntrl_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "trace: scale_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `min'.
 */
Panel_setting
min_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	trace_tcntrl_objects *ip = (trace_tcntrl_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	int	value = (int) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "trace: min_proc: value: %d\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `max'.
 */
Panel_setting
max_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	trace_tcntrl_objects *ip = (trace_tcntrl_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	int	value = (int) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "trace: max_proc: value: %d\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `tr_refresh'.
 */
void
trace_refresh_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	trace_trwin_objects *ip = (trace_trwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("trace: trace_refresh_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Event callback function for `trcanv'.
 */
Notify_value
trcanv_event_proc(win, event, arg, type)
	Xv_window	win;
	Event		*event;
	Notify_arg	arg;
	Notify_event_type type;
{
	trace_trwin_objects *ip = (trace_trwin_objects *) xv_get(xv_get(win, CANVAS_PAINT_CANVAS_WINDOW), XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "trace: trcanv_event_proc: event %d\n", event_id(event));
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * Repaint callback function for `trcanv'.
 */
void
trcanv_repaint_proc(canvas, paint_window, display, xid, rects)
	Canvas		canvas;
	Xv_window	paint_window;
	Display		*display;
	Window		xid;
	Xv_xrectlist	*rects;
{
	fputs("trace: trcanv_repaint_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `intg_eval'.
 */
void
integrate_eval_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	trace_trwin_objects *ip = (trace_trwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("trace: integrate_eval_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Repaint callback function for `intgcanv'.
 */
void
icanv_repaint_proc(canvas, paint_window, display, xid, rects)
	Canvas		canvas;
	Xv_window	paint_window;
	Display		*display;
	Window		xid;
	Xv_xrectlist	*rects;
{
	fputs("trace: icanv_repaint_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `options'.
 */
void
opt_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	trace_trwin_objects *ip = (trace_trwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("genial: opt_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `reset'.
 */
void
trace_opt_reset(item, event)
	Panel_item	item;
	Event		*event;
{
	trace_tcntrl_objects *ip = (trace_tcntrl_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("trace: trace_opt_reset\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}

/*
 * Notify callback function for `options'.
 */
void
trace_opt_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	trace_trwin_objects *ip = (trace_trwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("trace: trace_opt_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}
