/*
 * display_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `display.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "display_ui.h"

/*
 * Initialize an instance of object `ctrlwin'.
 */
display_ctrlwin_objects *
display_ctrlwin_objects_initialize(ip, owner)
	display_ctrlwin_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (display_ctrlwin_objects *) calloc(1, sizeof (display_ctrlwin_objects))))
		return (display_ctrlwin_objects *) NULL;
	if (!ip->ctrlwin)
		ip->ctrlwin = display_ctrlwin_ctrlwin_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = display_ctrlwin_controls1_create(ip, ip->ctrlwin);
	if (!ip->message2)
		ip->message2 = display_ctrlwin_message2_create(ip, ip->controls1);
	if (!ip->message1)
		ip->message1 = display_ctrlwin_message1_create(ip, ip->controls1);
	if (!ip->gamma)
		ip->gamma = display_ctrlwin_gamma_create(ip, ip->controls1);
	if (!ip->cmap_min)
		ip->cmap_min = display_ctrlwin_cmap_min_create(ip, ip->controls1);
	if (!ip->cmap_max)
		ip->cmap_max = display_ctrlwin_cmap_max_create(ip, ip->controls1);
	if (!ip->shrink_fac)
		ip->shrink_fac = display_ctrlwin_shrink_fac_create(ip, ip->controls1);
	return ip;
}

/*
 * Create object `ctrlwin' in the specified instance.
 */
Xv_opaque
display_ctrlwin_ctrlwin_create(ip, owner)
	display_ctrlwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 427,
		XV_HEIGHT, 184,
		XV_LABEL, "Display Control",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
display_ctrlwin_controls1_create(ip, owner)
	display_ctrlwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message2' in the specified instance.
 */
Xv_opaque
display_ctrlwin_message2_create(ip, owner)
	display_ctrlwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 16,
		PANEL_LABEL_STRING, "Note:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message1' in the specified instance.
 */
Xv_opaque
display_ctrlwin_message1_create(ip, owner)
	display_ctrlwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 24,
		XV_Y, 44,
		PANEL_LABEL_STRING, "These settings affect only the DISPLAY image, not the dataset.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `gamma' in the specified instance.
 */
Xv_opaque
display_ctrlwin_gamma_create(ip, owner)
	display_ctrlwin_objects	*ip;
	Xv_opaque	owner;
{
	extern void		gamma_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 80,
		PANEL_SLIDER_WIDTH, 150,
		PANEL_TICKS, 0,
		PANEL_LABEL_STRING, "Contrast:",
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, TRUE,
		PANEL_SHOW_RANGE, FALSE,
		PANEL_SHOW_VALUE, FALSE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 100,
		PANEL_VALUE, 0,
		PANEL_NOTIFY_PROC, gamma_proc,
		NULL);
	return obj;
}

/*
 * Create object `cmap_min' in the specified instance.
 */
Xv_opaque
display_ctrlwin_cmap_min_create(ip, owner)
	display_ctrlwin_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	cm_min_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 108,
		PANEL_VALUE_DISPLAY_LENGTH, 4,
		PANEL_VALUE_STORED_LENGTH, 8,
		PANEL_LABEL_STRING, "Min:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, cm_min_proc,
		NULL);
	return obj;
}

/*
 * Create object `cmap_max' in the specified instance.
 */
Xv_opaque
display_ctrlwin_cmap_max_create(ip, owner)
	display_ctrlwin_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	cm_max_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "display:cmap_max",
		XV_X, 140,
		XV_Y, 108,
		PANEL_VALUE_DISPLAY_LENGTH, 4,
		PANEL_VALUE_STORED_LENGTH, 8,
		PANEL_LABEL_STRING, "Max:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, cm_max_proc,
		NULL);
	return obj;
}

/*
 * Create object `shrink_fac' in the specified instance.
 */
Xv_opaque
display_ctrlwin_shrink_fac_create(ip, owner)
	display_ctrlwin_objects	*ip;
	Xv_opaque	owner;
{
	extern void		shrink_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 144,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, "Shrink Factor:",
		PANEL_NOTIFY_PROC, shrink_proc,
		PANEL_CHOICE_STRINGS,
			"1",
			"2",
			"4",
			"8",
			NULL,
		NULL);
	return obj;
}

