/*
 * trace_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `trace.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "trace_ui.h"

/*
 * Initialize an instance of object `tcntrl'.
 */
trace_tcntrl_objects *
trace_tcntrl_objects_initialize(ip, owner)
	trace_tcntrl_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (trace_tcntrl_objects *) calloc(1, sizeof (trace_tcntrl_objects))))
		return (trace_tcntrl_objects *) NULL;
	if (!ip->tcntrl)
		ip->tcntrl = trace_tcntrl_tcntrl_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = trace_tcntrl_controls1_create(ip, ip->tcntrl);
	if (!ip->traceno)
		ip->traceno = trace_tcntrl_traceno_create(ip, ip->controls1);
	if (!ip->radius)
		ip->radius = trace_tcntrl_radius_create(ip, ip->controls1);
	if (!ip->scale)
		ip->scale = trace_tcntrl_scale_create(ip, ip->controls1);
	if (!ip->min)
		ip->min = trace_tcntrl_min_create(ip, ip->controls1);
	if (!ip->max)
		ip->max = trace_tcntrl_max_create(ip, ip->controls1);
	return ip;
}

/*
 * Create object `tcntrl' in the specified instance.
 */
Xv_opaque
trace_tcntrl_tcntrl_create(ip, owner)
	trace_tcntrl_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 264,
		XV_HEIGHT, 131,
		XV_LABEL, "Trace Control",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
trace_tcntrl_controls1_create(ip, owner)
	trace_tcntrl_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `traceno' in the specified instance.
 */
Xv_opaque
trace_tcntrl_traceno_create(ip, owner)
	trace_tcntrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	traceno_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 20,
		PANEL_VALUE_DISPLAY_LENGTH, 2,
		PANEL_VALUE_STORED_LENGTH, 4,
		PANEL_LABEL_STRING, "Trace:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100,
		PANEL_MIN_VALUE, 1,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, traceno_proc,
		NULL);
	return obj;
}

/*
 * Create object `radius' in the specified instance.
 */
Xv_opaque
trace_tcntrl_radius_create(ip, owner)
	trace_tcntrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	rad_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 45,
		PANEL_VALUE_DISPLAY_LENGTH, 1,
		PANEL_VALUE_STORED_LENGTH, 1,
		PANEL_LABEL_STRING, "Averaging:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 10,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, rad_proc,
		NULL);
	return obj;
}

/*
 * Create object `scale' in the specified instance.
 */
Xv_opaque
trace_tcntrl_scale_create(ip, owner)
	trace_tcntrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		scale_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 70,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, "Scaling:",
		PANEL_NOTIFY_PROC, scale_proc,
		PANEL_CHOICE_STRINGS,
			"Image Scaled",
			"Trace Scaled",
			"Manual",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `min' in the specified instance.
 */
Xv_opaque
trace_tcntrl_min_create(ip, owner)
	trace_tcntrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	min_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 103,
		PANEL_VALUE_DISPLAY_LENGTH, 4,
		PANEL_VALUE_STORED_LENGTH, 4,
		PANEL_LABEL_STRING, "Min:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 255,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, min_proc,
		NULL);
	return obj;
}

/*
 * Create object `max' in the specified instance.
 */
Xv_opaque
trace_tcntrl_max_create(ip, owner)
	trace_tcntrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	max_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 144,
		XV_Y, 103,
		PANEL_VALUE_DISPLAY_LENGTH, 4,
		PANEL_VALUE_STORED_LENGTH, 8,
		PANEL_LABEL_STRING, "Max:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, max_proc,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `trwin'.
 */
trace_trwin_objects *
trace_trwin_objects_initialize(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (trace_trwin_objects *) calloc(1, sizeof (trace_trwin_objects))))
		return (trace_trwin_objects *) NULL;
	if (!ip->trwin)
		ip->trwin = trace_trwin_trwin_create(ip, owner);
	if (!ip->controls2)
		ip->controls2 = trace_trwin_controls2_create(ip, ip->trwin);
	if (!ip->mes1)
		ip->mes1 = trace_trwin_mes1_create(ip, ip->controls2);
	if (!ip->tr_refresh)
		ip->tr_refresh = trace_trwin_tr_refresh_create(ip, ip->controls2);
	if (!ip->mes3)
		ip->mes3 = trace_trwin_mes3_create(ip, ip->controls2);
	if (!ip->options)
		ip->options = trace_trwin_options_create(ip, ip->controls2);
	if (!ip->mes4)
		ip->mes4 = trace_trwin_mes4_create(ip, ip->controls2);
	if (!ip->trcanv)
		ip->trcanv = trace_trwin_trcanv_create(ip, ip->trwin);
	if (!ip->controls3)
		ip->controls3 = trace_trwin_controls3_create(ip, ip->trwin);
	if (!ip->integrate)
		ip->integrate = trace_trwin_integrate_create(ip, ip->controls3);
	if (!ip->intg_eval)
		ip->intg_eval = trace_trwin_intg_eval_create(ip, ip->controls3);
	return ip;
}

/*
 * Create object `trwin' in the specified instance.
 */
Xv_opaque
trace_trwin_trwin_create(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 268,
		XV_HEIGHT, 384,
		XV_LABEL, "GENIAL trace",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls2' in the specified instance.
 */
Xv_opaque
trace_trwin_controls2_create(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 67,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `mes1' in the specified instance.
 */
Xv_opaque
trace_trwin_mes1_create(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Value: 11111",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `tr_refresh' in the specified instance.
 */
Xv_opaque
trace_trwin_tr_refresh_create(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	extern void		trace_refresh_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 160,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Refresh",
		PANEL_NOTIFY_PROC, trace_refresh_proc,
		NULL);
	return obj;
}

/*
 * Create object `mes3' in the specified instance.
 */
Xv_opaque
trace_trwin_mes3_create(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 24,
		PANEL_LABEL_STRING, "Sum: 111111",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `options' in the specified instance.
 */
Xv_opaque
trace_trwin_options_create(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	extern void		trace_opt_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 160,
		XV_Y, 32,
		PANEL_LABEL_STRING, "Options...",
		PANEL_NOTIFY_PROC, trace_opt_proc,
		NULL);
	return obj;
}

/*
 * Create object `mes4' in the specified instance.
 */
Xv_opaque
trace_trwin_mes4_create(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 40,
		PANEL_LABEL_STRING, "Average: 11111",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `trcanv' in the specified instance.
 */
Xv_opaque
trace_trwin_trcanv_create(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	extern Notify_value	trcanv_event_proc();
	extern void	trcanv_repaint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, (int)xv_get(ip->controls2, XV_Y) +
		      (int)xv_get(ip->controls2, XV_HEIGHT),
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 275,
		CANVAS_REPAINT_PROC, trcanv_repaint_proc,
		CANVAS_X_PAINT_WINDOW, TRUE,
		NULL);
	xv_set(canvas_paint_window(obj), WIN_CONSUME_EVENTS,
		WIN_MOUSE_BUTTONS,
		LOC_MOVE,
		LOC_DRAG,
		LOC_WINENTER,
		LOC_WINEXIT,
		WIN_ASCII_EVENTS,
		WIN_LEFT_KEYS,
		WIN_RIGHT_KEYS,
		WIN_TOP_KEYS,
		NULL, NULL);
	notify_interpose_event_func(canvas_paint_window(obj),
		(Notify_func) trcanv_event_proc, NOTIFY_SAFE);
	/*
	 * This line is here for backwards compatibility. It will be
	 * removed for the next release.
	 */
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

/*
 * Create object `controls3' in the specified instance.
 */
Xv_opaque
trace_trwin_controls3_create(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, (int)xv_get(ip->trcanv, XV_Y) +
		      (int)xv_get(ip->trcanv, XV_HEIGHT),
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `integrate' in the specified instance.
 */
Xv_opaque
trace_trwin_integrate_create(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, "Select Integration region:",
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `intg_eval' in the specified instance.
 */
Xv_opaque
trace_trwin_intg_eval_create(ip, owner)
	trace_trwin_objects	*ip;
	Xv_opaque	owner;
{
	extern void		integrate_eval_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 216,
		XV_Y, 8,
		PANEL_LABEL_STRING, "eval",
		PANEL_NOTIFY_PROC, integrate_eval_proc,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `intgwin'.
 */
trace_intgwin_objects *
trace_intgwin_objects_initialize(ip, owner)
	trace_intgwin_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (trace_intgwin_objects *) calloc(1, sizeof (trace_intgwin_objects))))
		return (trace_intgwin_objects *) NULL;
	if (!ip->intgwin)
		ip->intgwin = trace_intgwin_intgwin_create(ip, owner);
	if (!ip->controls4)
		ip->controls4 = trace_intgwin_controls4_create(ip, ip->intgwin);
	if (!ip->message1)
		ip->message1 = trace_intgwin_message1_create(ip, ip->controls4);
	if (!ip->intgcanv)
		ip->intgcanv = trace_intgwin_intgcanv_create(ip, ip->intgwin);
	return ip;
}

/*
 * Create object `intgwin' in the specified instance.
 */
Xv_opaque
trace_intgwin_intgwin_create(ip, owner)
	trace_intgwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 212,
		XV_HEIGHT, 295,
		XV_LABEL, "Integrate",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls4' in the specified instance.
 */
Xv_opaque
trace_intgwin_controls4_create(ip, owner)
	trace_intgwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 32,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message1' in the specified instance.
 */
Xv_opaque
trace_intgwin_message1_create(ip, owner)
	trace_intgwin_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Integral Total: 9999999999",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `intgcanv' in the specified instance.
 */
Xv_opaque
trace_intgwin_intgcanv_create(ip, owner)
	trace_intgwin_objects	*ip;
	Xv_opaque	owner;
{
	extern void	icanv_repaint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, (int)xv_get(ip->controls4, XV_Y) +
		      (int)xv_get(ip->controls4, XV_HEIGHT),
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		CANVAS_REPAINT_PROC, icanv_repaint_proc,
		CANVAS_X_PAINT_WINDOW, TRUE,
		NULL);
	/*
	 * This line is here for backwards compatibility. It will be
	 * removed for the next release.
	 */
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

