/*
 * bp_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `bp.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/icon_load.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "bp_ui.h"

/*
 * Create object `menu_init' in the specified instance.

 */
Xv_opaque
bp_menu_init_create(ip, owner)
	caddr_t		*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Image Frame",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Edit Mask Frame",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Other Buffer",
			NULL,
		MENU_GEN_PIN_WINDOW, (Xv_opaque) ip[0], "",
		NULL);
	return obj;
}

/*
 * Create object `menu_segment' in the specified instance.

 */
Xv_opaque
bp_menu_segment_create(ip, owner)
	caddr_t		*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "2D Analysis",
			MENU_PULLRIGHT, bp_menu_2D_create(ip, NULL),
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "3D Analysis",
			MENU_PULLRIGHT, bp_menu_3D_create(ip, NULL),
			NULL,
		MENU_GEN_PIN_WINDOW, (Xv_opaque) ip[0], "",
		NULL);
	return obj;
}

/*
 * Create object `menu_2D' in the specified instance.

 */
Xv_opaque
bp_menu_2D_create(ip, owner)
	caddr_t		*ip;
	Xv_opaque	owner;
{
	extern Menu_item	test_proc_2d();
	extern Menu_item	menu_map_surf_fit();
	extern Menu_item	test_proc_2d();
	extern Menu_item	test_proc_2d();
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Area of Interest",
			MENU_GEN_PROC, test_proc_2d,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Surface Fitting",
			MENU_GEN_PROC, menu_map_surf_fit,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Symbolic Representation",
			MENU_GEN_PROC, test_proc_2d,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Convexity Analysis",
			MENU_GEN_PROC, test_proc_2d,
			NULL,
		MENU_GEN_PIN_WINDOW, (Xv_opaque) ip[0], "Menu 2D",
		NULL);
	return obj;
}

/*
 * Create object `menu_3D' in the specified instance.

 */
Xv_opaque
bp_menu_3D_create(ip, owner)
	caddr_t		*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Volume of Interest",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Volume Fitting",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Volumetric Description",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `menu_render' in the specified instance.

 */
Xv_opaque
bp_menu_render_create(ip, owner)
	caddr_t		*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Shading",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Map Intensity to Volume",
			NULL,
		MENU_GEN_PIN_WINDOW, (Xv_opaque) ip[0], "",
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `win'.
 */
bp_win_objects *
bp_win_objects_initialize(ip, owner)
	bp_win_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (bp_win_objects *) calloc(1, sizeof (bp_win_objects))))
		return (bp_win_objects *) NULL;
	if (!ip->win)
		ip->win = bp_win_win_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = bp_win_controls1_create(ip, ip->win);
	if (!ip->but_init)
		ip->but_init = bp_win_but_init_create(ip, ip->controls1);
	if (!ip->but_segment)
		ip->but_segment = bp_win_but_segment_create(ip, ip->controls1);
	if (!ip->but_render)
		ip->but_render = bp_win_but_render_create(ip, ip->controls1);
	if (!ip->but_close)
		ip->but_close = bp_win_but_close_create(ip, ip->controls1);
	return ip;
}

/*
 * Create object `win' in the specified instance.

 */
Xv_opaque
bp_win_win_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 354,
		XV_HEIGHT, 67,
		XV_LABEL, "Segal: Braham Parvin's Tools",
		FRAME_CLOSED, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.

 */
Xv_opaque
bp_win_controls1_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `but_init' in the specified instance.

 */
Xv_opaque
bp_win_but_init_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		XV_WIDTH, 110,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Initialization",
		PANEL_ITEM_MENU, bp_menu_init_create((caddr_t *) ip, NULL),
		NULL);
	return obj;
}

/*
 * Create object `but_segment' in the specified instance.

 */
Xv_opaque
bp_win_but_segment_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 128,
		XV_Y, 8,
		XV_WIDTH, 116,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Segmentation",
		PANEL_ITEM_MENU, bp_menu_segment_create((caddr_t *) ip, NULL),
		NULL);
	return obj;
}

/*
 * Create object `but_render' in the specified instance.

 */
Xv_opaque
bp_win_but_render_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 256,
		XV_Y, 8,
		XV_WIDTH, 94,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Rendering",
		PANEL_ITEM_MENU, bp_menu_render_create((caddr_t *) ip, NULL),
		NULL);
	return obj;
}

/*
 * Create object `but_close' in the specified instance.

 */
Xv_opaque
bp_win_but_close_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_bp();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 160,
		XV_Y, 44,
		XV_WIDTH, 51,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Close",
		PANEL_NOTIFY_PROC, map_bp,
		NULL);
	return obj;
}

