/*
 * image_reg_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `image_reg.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/icon_load.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "image_reg_ui.h"

/*
 * Initialize an instance of object `win'.
 */
image_reg_win_objects *
image_reg_win_objects_initialize(ip, owner)
	image_reg_win_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (image_reg_win_objects *) calloc(1, sizeof (image_reg_win_objects))))
		return (image_reg_win_objects *) NULL;
	if (!ip->win)
		ip->win = image_reg_win_win_create(ip, owner);
	if (!ip->controls)
		ip->controls = image_reg_win_controls_create(ip, ip->win);
	if (!ip->text_ref_frame)
		ip->text_ref_frame = image_reg_win_text_ref_frame_create(ip, ip->controls);
	if (!ip->but_save_image_frame)
		ip->but_save_image_frame = image_reg_win_but_save_image_frame_create(ip, ip->controls);
	if (!ip->msg_line_matching)
		ip->msg_line_matching = image_reg_win_msg_line_matching_create(ip, ip->controls);
	if (!ip->msg_manual)
		ip->msg_manual = image_reg_win_msg_manual_create(ip, ip->controls);
	if (!ip->msg_line1)
		ip->msg_line1 = image_reg_win_msg_line1_create(ip, ip->controls);
	if (!ip->msg_line2)
		ip->msg_line2 = image_reg_win_msg_line2_create(ip, ip->controls);
	if (!ip->but_line_scale)
		ip->but_line_scale = image_reg_win_but_line_scale_create(ip, ip->controls);
	if (!ip->but_scale)
		ip->but_scale = image_reg_win_but_scale_create(ip, ip->controls);
	if (!ip->text_scale_factor)
		ip->text_scale_factor = image_reg_win_text_scale_factor_create(ip, ip->controls);
	if (!ip->msg_line4)
		ip->msg_line4 = image_reg_win_msg_line4_create(ip, ip->controls);
	if (!ip->msg_line5)
		ip->msg_line5 = image_reg_win_msg_line5_create(ip, ip->controls);
	if (!ip->but_up)
		ip->but_up = image_reg_win_but_up_create(ip, ip->controls);
	if (!ip->but_point_translate)
		ip->but_point_translate = image_reg_win_but_point_translate_create(ip, ip->controls);
	if (!ip->but_left)
		ip->but_left = image_reg_win_but_left_create(ip, ip->controls);
	if (!ip->but_right)
		ip->but_right = image_reg_win_but_right_create(ip, ip->controls);
	if (!ip->set_trans_pixel_amount)
		ip->set_trans_pixel_amount = image_reg_win_set_trans_pixel_amount_create(ip, ip->controls);
	if (!ip->msg_translate)
		ip->msg_translate = image_reg_win_msg_translate_create(ip, ip->controls);
	if (!ip->but_down)
		ip->but_down = image_reg_win_but_down_create(ip, ip->controls);
	if (!ip->msg_line3)
		ip->msg_line3 = image_reg_win_msg_line3_create(ip, ip->controls);
	if (!ip->msg_line6)
		ip->msg_line6 = image_reg_win_msg_line6_create(ip, ip->controls);
	if (!ip->but_line_rotate)
		ip->but_line_rotate = image_reg_win_but_line_rotate_create(ip, ip->controls);
	if (!ip->but_rotate)
		ip->but_rotate = image_reg_win_but_rotate_create(ip, ip->controls);
	if (!ip->text_rotation_degrees)
		ip->text_rotation_degrees = image_reg_win_text_rotation_degrees_create(ip, ip->controls);
	if (!ip->but_close)
		ip->but_close = image_reg_win_but_close_create(ip, ip->controls);
	return ip;
}

/*
 * Create object `win' in the specified instance.

 */
Xv_opaque
image_reg_win_win_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 493,
		XV_HEIGHT, 253,
		XV_LABEL, "Segal: Image Registry",
		FRAME_CLOSED, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls' in the specified instance.

 */
Xv_opaque
image_reg_win_controls_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `text_ref_frame' in the specified instance.

 */
Xv_opaque
image_reg_win_text_ref_frame_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern Panel_setting	set_ref_frame_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 8,
		XV_WIDTH, 162,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "Reference Frame:",
		PANEL_VALUE_X, 138,
		PANEL_VALUE_Y, 8,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 4,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, set_ref_frame_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_save_image_frame' in the specified instance.

 */
Xv_opaque
image_reg_win_but_save_image_frame_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		write_image_frame();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 360,
		XV_Y, 16,
		XV_WIDTH, 129,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Save Image Frame",
		PANEL_NOTIFY_PROC, write_image_frame,
		NULL);
	return obj;
}

/*
 * Create object `msg_line_matching' in the specified instance.

 */
Xv_opaque
image_reg_win_msg_line_matching_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 32,
		XV_WIDTH, 100,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Line Matching:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `msg_manual' in the specified instance.

 */
Xv_opaque
image_reg_win_msg_manual_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 132,
		XV_Y, 32,
		XV_WIDTH, 54,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Manual:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `msg_line1' in the specified instance.

 */
Xv_opaque
image_reg_win_msg_line1_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 44,
		XV_WIDTH, 104,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "-------------",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `msg_line2' in the specified instance.

 */
Xv_opaque
image_reg_win_msg_line2_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 132,
		XV_Y, 44,
		XV_WIDTH, 360,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "---------------------------------------------",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `but_line_scale' in the specified instance.

 */
Xv_opaque
image_reg_win_but_line_scale_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		but_line_scale_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 72,
		XV_WIDTH, 78,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Line Scale",
		PANEL_NOTIFY_PROC, but_line_scale_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_scale' in the specified instance.

 */
Xv_opaque
image_reg_win_but_scale_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		but_manual_scale_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 136,
		XV_Y, 72,
		XV_WIDTH, 49,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Scale",
		PANEL_NOTIFY_PROC, but_manual_scale_proc,
		NULL);
	return obj;
}

/*
 * Create object `text_scale_factor' in the specified instance.

 */
Xv_opaque
image_reg_win_text_scale_factor_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern Panel_setting	set_scale_factor();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 196,
		XV_Y, 76,
		XV_WIDTH, 156,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "Scale Factor:",
		PANEL_VALUE_X, 288,
		PANEL_VALUE_Y, 76,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, set_scale_factor,
		NULL);
	return obj;
}

/*
 * Create object `msg_line4' in the specified instance.

 */
Xv_opaque
image_reg_win_msg_line4_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 104,
		XV_WIDTH, 104,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "-------------",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `msg_line5' in the specified instance.

 */
Xv_opaque
image_reg_win_msg_line5_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 129,
		XV_Y, 104,
		XV_WIDTH, 360,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "---------------------------------------------",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `but_up' in the specified instance.

 */
Xv_opaque
image_reg_win_but_up_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		but_up_translate_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 433,
		XV_Y, 116,
		XV_WIDTH, 26,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "^",
		PANEL_NOTIFY_PROC, but_up_translate_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_point_translate' in the specified instance.

 */
Xv_opaque
image_reg_win_but_point_translate_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		but_point_translate_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 136,
		XV_WIDTH, 111,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Point Translate",
		PANEL_NOTIFY_PROC, but_point_translate_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_left' in the specified instance.

 */
Xv_opaque
image_reg_win_but_left_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		but_left_translate_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 409,
		XV_Y, 136,
		XV_WIDTH, 26,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "<",
		PANEL_NOTIFY_PROC, but_left_translate_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_right' in the specified instance.

 */
Xv_opaque
image_reg_win_but_right_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		but_right_translate_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 457,
		XV_Y, 136,
		XV_WIDTH, 26,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, ">",
		PANEL_NOTIFY_PROC, but_right_translate_proc,
		NULL);
	return obj;
}

/*
 * Create object `set_trans_pixel_amount' in the specified instance.

 */
Xv_opaque
image_reg_win_set_trans_pixel_amount_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_trans_pixel_amount();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 144,
		XV_Y, 140,
		XV_WIDTH, 160,
		XV_HEIGHT, 20,
		PANEL_VALUE_X, 196,
		PANEL_VALUE_Y, 140,
		PANEL_SLIDER_WIDTH, 20,
		PANEL_LABEL_STRING, "Pixels:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 1,
		PANEL_MAX_VALUE, 20,
		PANEL_TICKS, 0,
		PANEL_NOTIFY_PROC, set_trans_pixel_amount,
		NULL);
	return obj;
}

/*
 * Create object `msg_translate' in the specified instance.

 */
Xv_opaque
image_reg_win_msg_translate_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 333,
		XV_Y, 140,
		XV_WIDTH, 69,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Translate:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `but_down' in the specified instance.

 */
Xv_opaque
image_reg_win_but_down_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		but_down_translate_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 433,
		XV_Y, 156,
		XV_WIDTH, 25,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "v",
		PANEL_NOTIFY_PROC, but_down_translate_proc,
		NULL);
	return obj;
}

/*
 * Create object `msg_line3' in the specified instance.

 */
Xv_opaque
image_reg_win_msg_line3_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 176,
		XV_WIDTH, 104,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "-------------",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `msg_line6' in the specified instance.

 */
Xv_opaque
image_reg_win_msg_line6_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 129,
		XV_Y, 176,
		XV_WIDTH, 360,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "---------------------------------------------",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `but_line_rotate' in the specified instance.

 */
Xv_opaque
image_reg_win_but_line_rotate_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		but_line_rotate_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 196,
		XV_WIDTH, 86,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Line Rotate",
		PANEL_NOTIFY_PROC, but_line_rotate_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_rotate' in the specified instance.

 */
Xv_opaque
image_reg_win_but_rotate_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		but_manual_rotate_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 136,
		XV_Y, 196,
		XV_WIDTH, 57,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Rotate",
		PANEL_NOTIFY_PROC, but_manual_rotate_proc,
		NULL);
	return obj;
}

/*
 * Create object `text_rotation_degrees' in the specified instance.

 */
Xv_opaque
image_reg_win_text_rotation_degrees_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern Panel_setting	set_rotation_degrees();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 208,
		XV_Y, 200,
		XV_WIDTH, 192,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "Rotation Degrees:",
		PANEL_VALUE_X, 336,
		PANEL_VALUE_Y, 200,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, set_rotation_degrees,
		NULL);
	return obj;
}

/*
 * Create object `but_close' in the specified instance.

 */
Xv_opaque
image_reg_win_but_close_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_image_reg();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 208,
		XV_Y, 224,
		XV_WIDTH, 51,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Close",
		PANEL_NOTIFY_PROC, map_image_reg,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `pop_ref_frame'.
 */
image_reg_pop_ref_frame_objects *
image_reg_pop_ref_frame_objects_initialize(ip, owner)
	image_reg_pop_ref_frame_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (image_reg_pop_ref_frame_objects *) calloc(1, sizeof (image_reg_pop_ref_frame_objects))))
		return (image_reg_pop_ref_frame_objects *) NULL;
	if (!ip->pop_ref_frame)
		ip->pop_ref_frame = image_reg_pop_ref_frame_pop_ref_frame_create(ip, owner);
	if (!ip->canv_ref_frame)
		ip->canv_ref_frame = image_reg_pop_ref_frame_canv_ref_frame_create(ip, ip->pop_ref_frame);
	return ip;
}

/*
 * Create object `pop_ref_frame' in the specified instance.

 */
Xv_opaque
image_reg_pop_ref_frame_pop_ref_frame_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 190,
		XV_HEIGHT, 64,
		XV_LABEL, "Reference Frame",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `canv_ref_frame' in the specified instance.

 */
Xv_opaque
image_reg_pop_ref_frame_canv_ref_frame_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern Notify_value	ref_frame_mouse_proc();
	extern void	ref_frame_image_repaint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, 64,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		CANVAS_REPAINT_PROC, ref_frame_image_repaint_proc,
		NULL);
	xv_set(canvas_paint_window(obj), WIN_CONSUME_EVENTS,
		WIN_MOUSE_BUTTONS,
		LOC_DRAG,
		NULL, NULL);
	notify_interpose_event_func(canvas_paint_window(obj),
		(Notify_func) ref_frame_mouse_proc, NOTIFY_SAFE);
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

