#ifndef	load_save_HEADER
#define	load_save_HEADER

/*
 * load_save_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `load_save.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	pop_load;
	Xv_opaque	controls_load;
	Xv_opaque	load_which;
	Xv_opaque	load_dname;
	Xv_opaque	load_fname;
	Xv_opaque	but_load;
} load_save_pop_load_objects;

extern load_save_pop_load_objects	*load_save_pop_load_objects_initialize();

extern Xv_opaque	load_save_pop_load_pop_load_create();
extern Xv_opaque	load_save_pop_load_controls_load_create();
extern Xv_opaque	load_save_pop_load_load_which_create();
extern Xv_opaque	load_save_pop_load_load_dname_create();
extern Xv_opaque	load_save_pop_load_load_fname_create();
extern Xv_opaque	load_save_pop_load_but_load_create();

typedef struct {
	Xv_opaque	pop_create;
	Xv_opaque	controls_create;
	Xv_opaque	create_dname;
	Xv_opaque	create_fname;
	Xv_opaque	but_create;
} load_save_pop_create_objects;

extern load_save_pop_create_objects	*load_save_pop_create_objects_initialize();

extern Xv_opaque	load_save_pop_create_pop_create_create();
extern Xv_opaque	load_save_pop_create_controls_create_create();
extern Xv_opaque	load_save_pop_create_create_dname_create();
extern Xv_opaque	load_save_pop_create_create_fname_create();
extern Xv_opaque	load_save_pop_create_but_create_create();
#endif
