#ifndef	mask_log_HEADER
#define	mask_log_HEADER

/*
 * mask_log_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `mask_log.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	win;
	Xv_opaque	controls;
	Xv_opaque	msg_mask_filenames;
	Xv_opaque	msg_masks_loaded;
	Xv_opaque	ls_mask_filenames;
	Xv_opaque	set_mask_type;
	Xv_opaque	set_which_apply_first;
	Xv_opaque	set_mask_color;
	Xv_opaque	but_close;
} mask_log_win_objects;

extern mask_log_win_objects	*mask_log_win_objects_initialize();

extern Xv_opaque	mask_log_win_win_create();
extern Xv_opaque	mask_log_win_controls_create();
extern Xv_opaque	mask_log_win_msg_mask_filenames_create();
extern Xv_opaque	mask_log_win_msg_masks_loaded_create();
extern Xv_opaque	mask_log_win_ls_mask_filenames_create();
extern Xv_opaque	mask_log_win_set_mask_type_create();
extern Xv_opaque	mask_log_win_set_which_apply_first_create();
extern Xv_opaque	mask_log_win_set_mask_color_create();
extern Xv_opaque	mask_log_win_but_close_create();
#endif
