/*
 * mask_log_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `mask_log.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/icon_load.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "mask_log_ui.h"

/*
 * Initialize an instance of object `win'.
 */
mask_log_win_objects *
mask_log_win_objects_initialize(ip, owner)
	mask_log_win_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (mask_log_win_objects *) calloc(1, sizeof (mask_log_win_objects))))
		return (mask_log_win_objects *) NULL;
	if (!ip->win)
		ip->win = mask_log_win_win_create(ip, owner);
	if (!ip->controls)
		ip->controls = mask_log_win_controls_create(ip, ip->win);
	if (!ip->msg_mask_filenames)
		ip->msg_mask_filenames = mask_log_win_msg_mask_filenames_create(ip, ip->controls);
	if (!ip->msg_masks_loaded)
		ip->msg_masks_loaded = mask_log_win_msg_masks_loaded_create(ip, ip->controls);
	if (!ip->ls_mask_filenames)
		ip->ls_mask_filenames = mask_log_win_ls_mask_filenames_create(ip, ip->controls);
	if (!ip->set_mask_type)
		ip->set_mask_type = mask_log_win_set_mask_type_create(ip, ip->controls);
	if (!ip->set_which_apply_first)
		ip->set_which_apply_first = mask_log_win_set_which_apply_first_create(ip, ip->controls);
	if (!ip->set_mask_color)
		ip->set_mask_color = mask_log_win_set_mask_color_create(ip, ip->controls);
	if (!ip->but_close)
		ip->but_close = mask_log_win_but_close_create(ip, ip->controls);
	return ip;
}

/*
 * Create object `win' in the specified instance.

 */
Xv_opaque
mask_log_win_win_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 458,
		XV_HEIGHT, 327,
		XV_LABEL, "Segal: Mask Log",
		FRAME_CLOSED, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls' in the specified instance.

 */
Xv_opaque
mask_log_win_controls_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern Notify_value	edit_mask_defined();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	xv_set(obj, WIN_CONSUME_EVENTS,
		LOC_WINEXIT,
		NULL, NULL);
	notify_interpose_event_func(obj,
		(Notify_func) edit_mask_defined, NOTIFY_SAFE);
	return obj;
}

/*
 * Create object `msg_mask_filenames' in the specified instance.

 */
Xv_opaque
mask_log_win_msg_mask_filenames_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 8,
		XV_WIDTH, 108,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Mask File Name",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `msg_masks_loaded' in the specified instance.

 */
Xv_opaque
mask_log_win_msg_masks_loaded_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 280,
		XV_Y, 8,
		XV_WIDTH, 99,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Masks Loaded:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `ls_mask_filenames' in the specified instance.

 */
Xv_opaque
mask_log_win_ls_mask_filenames_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		update_mask_log_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 28,
		PANEL_LIST_WIDTH, 400,
		XV_HEIGHT, 182,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LIST_DISPLAY_ROWS, 9,
		PANEL_READ_ONLY, FALSE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, TRUE,
		PANEL_NOTIFY_PROC, update_mask_log_proc,
		NULL);
	return obj;
}

/*
 * Create object `set_mask_type' in the specified instance.

 */
Xv_opaque
mask_log_win_set_mask_type_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_mask_type();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 220,
		XV_WIDTH, 355,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 105,
		PANEL_VALUE_Y, 220,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Mask Type:",
		PANEL_NOTIFY_PROC, set_mask_type,
		PANEL_CHOICE_STRINGS,
			"Not Applied",
			"Edit",
			"Exclusive",
			"Inclusive",
			0,
		NULL);
	return obj;
}

/*
 * Create object `set_which_apply_first' in the specified instance.

 */
Xv_opaque
mask_log_win_set_which_apply_first_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 54,
		XV_Y, 248,
		XV_WIDTH, 317,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 105,
		PANEL_VALUE_Y, 248,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Apply:",
		PANEL_CHOICE_STRINGS,
			"Exclusive, Inclusive",
			"Inclusive, Exclusive",
			0,
		NULL);
	return obj;
}

/*
 * Create object `set_mask_color' in the specified instance.

 */
Xv_opaque
mask_log_win_set_mask_color_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_mask_color();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 18,
		XV_Y, 276,
		XV_WIDTH, 277,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 105,
		PANEL_VALUE_Y, 276,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Mask Color:",
		PANEL_NOTIFY_PROC, set_mask_color,
		PANEL_CHOICE_STRINGS,
			"Green",
			"Red",
			"Yellow",
			"Blue",
			0,
		NULL);
	return obj;
}

/*
 * Create object `but_close' in the specified instance.

 */
Xv_opaque
mask_log_win_but_close_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_mask_log();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 200,
		XV_Y, 304,
		XV_WIDTH, 51,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Close",
		PANEL_NOTIFY_PROC, map_mask_log,
		NULL);
	return obj;
}

