/*
 * mask_control_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `mask_control.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/icon_load.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "mask_control_ui.h"

/*
 * Create object `mask_menu' in the specified instance.

 */
Xv_opaque
mask_control_mask_menu_create(ip, owner)
	caddr_t		*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Fill Mask",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Clear Mask",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Invert Mask",
			NULL,
		MENU_GEN_PIN_WINDOW, (Xv_opaque) ip[0], "Mask Operations Menu",
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `win'.
 */
mask_control_win_objects *
mask_control_win_objects_initialize(ip, owner)
	mask_control_win_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (mask_control_win_objects *) calloc(1, sizeof (mask_control_win_objects))))
		return (mask_control_win_objects *) NULL;
	if (!ip->win)
		ip->win = mask_control_win_win_create(ip, owner);
	if (!ip->controls)
		ip->controls = mask_control_win_controls_create(ip, ip->win);
	if (!ip->display_type)
		ip->display_type = mask_control_win_display_type_create(ip, ip->controls);
	if (!ip->but_threshold)
		ip->but_threshold = mask_control_win_but_threshold_create(ip, ip->controls);
	if (!ip->but_fill)
		ip->but_fill = mask_control_win_but_fill_create(ip, ip->controls);
	if (!ip->but_clear)
		ip->but_clear = mask_control_win_but_clear_create(ip, ip->controls);
	if (!ip->but_invert)
		ip->but_invert = mask_control_win_but_invert_create(ip, ip->controls);
	if (!ip->but_poly)
		ip->but_poly = mask_control_win_but_poly_create(ip, ip->controls);
	if (!ip->msg_growth)
		ip->msg_growth = mask_control_win_msg_growth_create(ip, ip->controls);
	if (!ip->but_original)
		ip->but_original = mask_control_win_but_original_create(ip, ip->controls);
	if (!ip->but_undo)
		ip->but_undo = mask_control_win_but_undo_create(ip, ip->controls);
	if (!ip->but_stop)
		ip->but_stop = mask_control_win_but_stop_create(ip, ip->controls);
	if (!ip->but_grow)
		ip->but_grow = mask_control_win_but_grow_create(ip, ip->controls);
	if (!ip->set_portion)
		ip->set_portion = mask_control_win_set_portion_create(ip, ip->controls);
	if (!ip->set_extent_3D)
		ip->set_extent_3D = mask_control_win_set_extent_3D_create(ip, ip->controls);
	if (!ip->set_region)
		ip->set_region = mask_control_win_set_region_create(ip, ip->controls);
	if (!ip->beg_frame)
		ip->beg_frame = mask_control_win_beg_frame_create(ip, ip->controls);
	if (!ip->end_frame)
		ip->end_frame = mask_control_win_end_frame_create(ip, ip->controls);
	if (!ip->grow_gradient)
		ip->grow_gradient = mask_control_win_grow_gradient_create(ip, ip->controls);
	if (!ip->msg_matrix)
		ip->msg_matrix = mask_control_win_msg_matrix_create(ip, ip->controls);
	if (!ip->set_matrix_type)
		ip->set_matrix_type = mask_control_win_set_matrix_type_create(ip, ip->controls);
	if (!ip->set_apply_in)
		ip->set_apply_in = mask_control_win_set_apply_in_create(ip, ip->controls);
	if (!ip->set_matrix_size)
		ip->set_matrix_size = mask_control_win_set_matrix_size_create(ip, ip->controls);
	if (!ip->msg_threshold)
		ip->msg_threshold = mask_control_win_msg_threshold_create(ip, ip->controls);
	if (!ip->grow_threshold_high)
		ip->grow_threshold_high = mask_control_win_grow_threshold_high_create(ip, ip->controls);
	if (!ip->grow_threshold_low)
		ip->grow_threshold_low = mask_control_win_grow_threshold_low_create(ip, ip->controls);
	if (!ip->but_close)
		ip->but_close = mask_control_win_but_close_create(ip, ip->controls);
	return ip;
}

/*
 * Create object `win' in the specified instance.

 */
Xv_opaque
mask_control_win_win_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 416,
		XV_HEIGHT, 375,
		XV_LABEL, "Segal : Mask Control",
		FRAME_CLOSED, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls' in the specified instance.

 */
Xv_opaque
mask_control_win_controls_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `display_type' in the specified instance.

 */
Xv_opaque
mask_control_win_display_type_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		change_image_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		XV_WIDTH, 207,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 72,
		PANEL_VALUE_Y, 8,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Display:",
		PANEL_NOTIFY_PROC, change_image_proc,
		PANEL_CHOICE_STRINGS,
			"Image",
			"Mask",
			"Both",
			0,
		NULL);
	return obj;
}

/*
 * Create object `but_threshold' in the specified instance.

 */
Xv_opaque
mask_control_win_but_threshold_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_threshold();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 326,
		XV_Y, 12,
		XV_WIDTH, 79,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Threshold",
		PANEL_NOTIFY_PROC, map_threshold,
		NULL);
	return obj;
}

/*
 * Create object `but_fill' in the specified instance.

 */
Xv_opaque
mask_control_win_but_fill_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		mask_fill_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 9,
		XV_Y, 44,
		XV_WIDTH, 37,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Fill",
		PANEL_NOTIFY_PROC, mask_fill_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_clear' in the specified instance.

 */
Xv_opaque
mask_control_win_but_clear_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		mask_clear_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 56,
		XV_Y, 44,
		XV_WIDTH, 50,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Clear",
		PANEL_NOTIFY_PROC, mask_clear_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_invert' in the specified instance.

 */
Xv_opaque
mask_control_win_but_invert_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		mask_invert_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 116,
		XV_Y, 44,
		XV_WIDTH, 54,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Invert",
		PANEL_NOTIFY_PROC, mask_invert_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_poly' in the specified instance.

 */
Xv_opaque
mask_control_win_but_poly_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		poly_mask_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 304,
		XV_Y, 44,
		XV_WIDTH, 101,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Polygon Mask",
		PANEL_NOTIFY_PROC, poly_mask_proc,
		NULL);
	return obj;
}

/*
 * Create object `msg_growth' in the specified instance.

 */
Xv_opaque
mask_control_win_msg_growth_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 10,
		XV_Y, 68,
		XV_WIDTH, 395,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "-------------------Growth Options-----------------",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `but_original' in the specified instance.

 */
Xv_opaque
mask_control_win_but_original_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		original_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 84,
		XV_WIDTH, 67,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Original",
		PANEL_NOTIFY_PROC, original_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_undo' in the specified instance.

 */
Xv_opaque
mask_control_win_but_undo_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		undo_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 88,
		XV_Y, 84,
		XV_WIDTH, 50,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Undo",
		PANEL_NOTIFY_PROC, undo_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_stop' in the specified instance.

 */
Xv_opaque
mask_control_win_but_stop_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		grow_stop_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 296,
		XV_Y, 84,
		XV_WIDTH, 45,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Stop",
		PANEL_EVENT_PROC, grow_stop_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_grow' in the specified instance.

 */
Xv_opaque
mask_control_win_but_grow_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		grow_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 354,
		XV_Y, 84,
		XV_WIDTH, 50,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Grow",
		PANEL_NOTIFY_PROC, grow_proc,
		NULL);
	return obj;
}

/*
 * Create object `set_portion' in the specified instance.

 */
Xv_opaque
mask_control_win_set_portion_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		portion_set_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 36,
		XV_Y, 110,
		XV_WIDTH, 170,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 97,
		PANEL_VALUE_Y, 110,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Portion:",
		PANEL_NOTIFY_PROC, portion_set_proc,
		PANEL_CHOICE_STRINGS,
			"Whole",
			"Region",
			0,
		NULL);
	return obj;
}

/*
 * Create object `set_extent_3D' in the specified instance.

 */
Xv_opaque
mask_control_win_set_extent_3D_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_grow_extent_3D();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 42,
		XV_Y, 136,
		XV_WIDTH, 211,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 95,
		PANEL_VALUE_Y, 136,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Extent:",
		PANEL_NOTIFY_PROC, set_grow_extent_3D,
		PANEL_CHOICE_STRINGS,
			"Grow In",
			"Grow In, Out",
			0,
		NULL);
	return obj;
}

/*
 * Create object `set_region' in the specified instance.

 */
Xv_opaque
mask_control_win_set_region_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		draw_hints_grow_region();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 50,
		XV_Y, 164,
		XV_WIDTH, 295,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 95,
		PANEL_VALUE_Y, 164,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "From:",
		PANEL_NOTIFY_PROC, draw_hints_grow_region,
		PANEL_CHOICE_STRINGS,
			"Seed Points In This Frame",
			"Beginning Frame to Ending Frame",
			"This Frame --to-> Previous Frame",
			"This Frame --to-> Next Frame",
			0,
		NULL);
	return obj;
}

/*
 * Create object `beg_frame' in the specified instance.

 */
Xv_opaque
mask_control_win_beg_frame_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 4,
		XV_Y, 188,
		XV_WIDTH, 155,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "From Frame:",
		PANEL_VALUE_X, 95,
		PANEL_VALUE_Y, 188,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `end_frame' in the specified instance.

 */
Xv_opaque
mask_control_win_end_frame_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 170,
		XV_Y, 188,
		XV_WIDTH, 138,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "To Frame:",
		PANEL_VALUE_X, 244,
		PANEL_VALUE_Y, 188,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `grow_gradient' in the specified instance.

 */
Xv_opaque
mask_control_win_grow_gradient_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_grow_gradient();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 25,
		XV_Y, 216,
		XV_WIDTH, 383,
		XV_HEIGHT, 20,
		PANEL_VALUE_X, 94,
		PANEL_VALUE_Y, 216,
		PANEL_SLIDER_WIDTH, 256,
		PANEL_LABEL_STRING, "Gradient:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, FALSE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 255,
		PANEL_TICKS, 0,
		PANEL_NOTIFY_PROC, set_grow_gradient,
		NULL);
	return obj;
}

/*
 * Create object `msg_matrix' in the specified instance.

 */
Xv_opaque
mask_control_win_msg_matrix_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 10,
		XV_Y, 236,
		XV_WIDTH, 395,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Matrix--------------------------------------------",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `set_matrix_type' in the specified instance.

 */
Xv_opaque
mask_control_win_set_matrix_type_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 50,
		XV_Y, 248,
		XV_WIDTH, 258,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 95,
		PANEL_VALUE_Y, 248,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Type:",
		PANEL_CHOICE_STRINGS,
			"Simple Gradient",
			"Sobel (3x3 max)  ",
			"Laplacian (3x3 max)",
			"Kasvand Laplacian (5x5 max)",
			0,
		NULL);
	return obj;
}

/*
 * Create object `set_apply_in' in the specified instance.

 */
Xv_opaque
mask_control_win_set_apply_in_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_grow_apply_in();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 266,
		XV_Y, 248,
		XV_WIDTH, 143,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 335,
		PANEL_VALUE_Y, 248,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Apply In:",
		PANEL_NOTIFY_PROC, set_grow_apply_in,
		PANEL_CHOICE_STRINGS,
			"Frame",
			"3-d",
			0,
		NULL);
	return obj;
}

/*
 * Create object `set_matrix_size' in the specified instance.

 */
Xv_opaque
mask_control_win_set_matrix_size_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_grow_matrix_size();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 56,
		XV_Y, 268,
		XV_WIDTH, 106,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 95,
		PANEL_VALUE_Y, 268,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Size:",
		PANEL_NOTIFY_PROC, set_grow_matrix_size,
		PANEL_CHOICE_STRINGS,
			"3 x 3",
			"5 x 5",
			"7 x 7",
			"9 x 9",
			0,
		NULL);
	return obj;
}

/*
 * Create object `msg_threshold' in the specified instance.

 */
Xv_opaque
mask_control_win_msg_threshold_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 10,
		XV_Y, 292,
		XV_WIDTH, 393,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Threshold Values----------------------------------",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `grow_threshold_high' in the specified instance.

 */
Xv_opaque
mask_control_win_grow_threshold_high_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_grow_threshold_high();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 37,
		XV_Y, 310,
		XV_WIDTH, 367,
		XV_HEIGHT, 20,
		PANEL_VALUE_X, 90,
		PANEL_VALUE_Y, 310,
		PANEL_SLIDER_WIDTH, 256,
		PANEL_LABEL_STRING, "Upper:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, FALSE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 255,
		PANEL_TICKS, 0,
		PANEL_NOTIFY_PROC, set_grow_threshold_high,
		NULL);
	return obj;
}

/*
 * Create object `grow_threshold_low' in the specified instance.

 */
Xv_opaque
mask_control_win_grow_threshold_low_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_grow_threshold_low();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 37,
		XV_Y, 330,
		XV_WIDTH, 366,
		XV_HEIGHT, 20,
		PANEL_VALUE_X, 89,
		PANEL_VALUE_Y, 330,
		PANEL_SLIDER_WIDTH, 256,
		PANEL_LABEL_STRING, "Lower:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, FALSE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 255,
		PANEL_TICKS, 0,
		PANEL_NOTIFY_PROC, set_grow_threshold_low,
		NULL);
	return obj;
}

/*
 * Create object `but_close' in the specified instance.

 */
Xv_opaque
mask_control_win_but_close_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_mask_control();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 190,
		XV_Y, 352,
		XV_WIDTH, 51,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Close",
		PANEL_NOTIFY_PROC, map_mask_control,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `pop_polygon'.
 */
mask_control_pop_polygon_objects *
mask_control_pop_polygon_objects_initialize(ip, owner)
	mask_control_pop_polygon_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (mask_control_pop_polygon_objects *) calloc(1, sizeof (mask_control_pop_polygon_objects))))
		return (mask_control_pop_polygon_objects *) NULL;
	if (!ip->pop_polygon)
		ip->pop_polygon = mask_control_pop_polygon_pop_polygon_create(ip, owner);
	if (!ip->controls_poly)
		ip->controls_poly = mask_control_pop_polygon_controls_poly_create(ip, ip->pop_polygon);
	if (!ip->msg_directions)
		ip->msg_directions = mask_control_pop_polygon_msg_directions_create(ip, ip->controls_poly);
	if (!ip->set_polyfunct)
		ip->set_polyfunct = mask_control_pop_polygon_set_polyfunct_create(ip, ip->controls_poly);
	if (!ip->msg_poly)
		ip->msg_poly = mask_control_pop_polygon_msg_poly_create(ip, ip->controls_poly);
	if (!ip->but_apply)
		ip->but_apply = mask_control_pop_polygon_but_apply_create(ip, ip->controls_poly);
	return ip;
}

/*
 * Create object `pop_polygon' in the specified instance.

 */
Xv_opaque
mask_control_pop_polygon_pop_polygon_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 400,
		XV_HEIGHT, 132,
		XV_LABEL, "Segal : Polygon Mask",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls_poly' in the specified instance.

 */
Xv_opaque
mask_control_pop_polygon_controls_poly_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `msg_directions' in the specified instance.

 */
Xv_opaque
mask_control_pop_polygon_msg_directions_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 24,
		XV_Y, 24,
		XV_WIDTH, 353,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Select Points for the Polygon, then select a function",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `set_polyfunct' in the specified instance.

 */
Xv_opaque
mask_control_pop_polygon_set_polyfunct_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 52,
		XV_Y, 56,
		XV_WIDTH, 132,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 61,
		PANEL_VALUE_Y, 56,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_CHOICE_STRINGS,
			"Show",
			"Fill",
			"Clear",
			0,
		NULL);
	return obj;
}

/*
 * Create object `msg_poly' in the specified instance.

 */
Xv_opaque
mask_control_pop_polygon_msg_poly_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 208,
		XV_Y, 60,
		XV_WIDTH, 135,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "The Polygon Region",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `but_apply' in the specified instance.

 */
Xv_opaque
mask_control_pop_polygon_but_apply_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 168,
		XV_Y, 96,
		XV_WIDTH, 53,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Apply",
		NULL);
	return obj;
}

