/*
 * segal_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `segal.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/icon_load.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "segal_ui.h"

/*
 * Create object `menu_file' in the specified instance.

 */
Xv_opaque
segal_menu_file_create(ip, owner)
	caddr_t		*ip;
	Xv_opaque	owner;
{
	extern Menu_item	menu_load_proc();
	extern Menu_item	menu_save_frame_proc();
	extern Menu_item	menu_create_proc();
	extern Menu_item	menu_quit_proc();
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Load ...",
			MENU_GEN_PROC, menu_load_proc,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Save Frame",
			MENU_GEN_PROC, menu_save_frame_proc,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Create Mask",
			MENU_GEN_PROC, menu_create_proc,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Quit",
			MENU_GEN_PROC, menu_quit_proc,
			NULL,
		MENU_DEFAULT, 1,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `win'.
 */
segal_win_objects *
segal_win_objects_initialize(ip, owner)
	segal_win_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (segal_win_objects *) calloc(1, sizeof (segal_win_objects))))
		return (segal_win_objects *) NULL;
	if (!ip->win)
		ip->win = segal_win_win_create(ip, owner);
	if (!ip->controls)
		ip->controls = segal_win_controls_create(ip, ip->win);
	if (!ip->but_file)
		ip->but_file = segal_win_but_file_create(ip, ip->controls);
	if (!ip->msg_image_fname)
		ip->msg_image_fname = segal_win_msg_image_fname_create(ip, ip->controls);
	if (!ip->msg_image_size)
		ip->msg_image_size = segal_win_msg_image_size_create(ip, ip->controls);
	if (!ip->msg_mask_fname)
		ip->msg_mask_fname = segal_win_msg_mask_fname_create(ip, ip->controls);
	if (!ip->but_undo)
		ip->but_undo = segal_win_but_undo_create(ip, ip->controls);
	if (!ip->msg_pixedit)
		ip->msg_pixedit = segal_win_msg_pixedit_create(ip, ip->controls);
	if (!ip->msg_pixel_value)
		ip->msg_pixel_value = segal_win_msg_pixel_value_create(ip, ip->controls);
	if (!ip->but_original)
		ip->but_original = segal_win_but_original_create(ip, ip->controls);
	if (!ip->but_edit)
		ip->but_edit = segal_win_but_edit_create(ip, ip->controls);
	if (!ip->but_mask_log)
		ip->but_mask_log = segal_win_but_mask_log_create(ip, ip->controls);
	if (!ip->but_image_reg)
		ip->but_image_reg = segal_win_but_image_reg_create(ip, ip->controls);
	if (!ip->but_filter)
		ip->but_filter = segal_win_but_filter_create(ip, ip->controls);
	if (!ip->but_frame)
		ip->but_frame = segal_win_but_frame_create(ip, ip->controls);
	if (!ip->but_display)
		ip->but_display = segal_win_but_display_create(ip, ip->controls);
	if (!ip->but_mask)
		ip->but_mask = segal_win_but_mask_create(ip, ip->controls);
	if (!ip->but_bp)
		ip->but_bp = segal_win_but_bp_create(ip, ip->controls);
	if (!ip->msg_hint)
		ip->msg_hint = segal_win_msg_hint_create(ip, ip->controls);
	return ip;
}

/*
 * Create object `win' in the specified instance.

 */
Xv_opaque
segal_win_win_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 451,
		XV_HEIGHT, 203,
		XV_LABEL, "Segal (SEGmentation AnaLyzer) ver 3.0 beta",
		FRAME_CLOSED, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls' in the specified instance.

 */
Xv_opaque
segal_win_controls_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `but_file' in the specified instance.

 */
Xv_opaque
segal_win_but_file_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 10,
		XV_Y, 8,
		XV_WIDTH, 78,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "File I/O",
		PANEL_ITEM_MENU, segal_menu_file_create((caddr_t *) ip, NULL),
		NULL);
	return obj;
}

/*
 * Create object `msg_image_fname' in the specified instance.

 */
Xv_opaque
segal_win_msg_image_fname_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 99,
		XV_Y, 16,
		XV_WIDTH, 45,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Image:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `msg_image_size' in the specified instance.

 */
Xv_opaque
segal_win_msg_image_size_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 67,
		XV_Y, 36,
		XV_WIDTH, 77,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Image Size:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `msg_mask_fname' in the specified instance.

 */
Xv_opaque
segal_win_msg_mask_fname_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 75,
		XV_Y, 56,
		XV_WIDTH, 69,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Edit Mask:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `but_undo' in the specified instance.

 */
Xv_opaque
segal_win_but_undo_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		undo_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 388,
		XV_Y, 68,
		XV_WIDTH, 50,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Undo",
		PANEL_NOTIFY_PROC, undo_proc,
		NULL);
	return obj;
}

/*
 * Create object `msg_pixedit' in the specified instance.

 */
Xv_opaque
segal_win_msg_pixedit_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 32,
		XV_Y, 76,
		XV_WIDTH, 112,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Edit Region Size:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `msg_pixel_value' in the specified instance.

 */
Xv_opaque
segal_win_msg_pixel_value_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 65,
		XV_Y, 96,
		XV_WIDTH, 79,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Pixel Value:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `but_original' in the specified instance.

 */
Xv_opaque
segal_win_but_original_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		original_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 376,
		XV_Y, 96,
		XV_WIDTH, 67,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Original",
		PANEL_NOTIFY_PROC, original_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_edit' in the specified instance.

 */
Xv_opaque
segal_win_but_edit_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_edit_win();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 124,
		XV_WIDTH, 95,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Edit Window",
		PANEL_NOTIFY_PROC, map_edit_win,
		NULL);
	return obj;
}

/*
 * Create object `but_mask_log' in the specified instance.

 */
Xv_opaque
segal_win_but_mask_log_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_mask_log();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 124,
		XV_Y, 124,
		XV_WIDTH, 73,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Mask Log",
		PANEL_NOTIFY_PROC, map_mask_log,
		NULL);
	return obj;
}

/*
 * Create object `but_image_reg' in the specified instance.

 */
Xv_opaque
segal_win_but_image_reg_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_image_reg();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 244,
		XV_Y, 124,
		XV_WIDTH, 108,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Image Registry",
		PANEL_NOTIFY_PROC, map_image_reg,
		NULL);
	return obj;
}

/*
 * Create object `but_filter' in the specified instance.

 */
Xv_opaque
segal_win_but_filter_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_filter();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 388,
		XV_Y, 124,
		XV_WIDTH, 56,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Filters",
		PANEL_NOTIFY_PROC, map_filter,
		NULL);
	return obj;
}

/*
 * Create object `but_frame' in the specified instance.

 */
Xv_opaque
segal_win_but_frame_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_frame_control();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 156,
		XV_WIDTH, 105,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Frame Control",
		PANEL_NOTIFY_PROC, map_frame_control,
		NULL);
	return obj;
}

/*
 * Create object `but_display' in the specified instance.

 */
Xv_opaque
segal_win_but_display_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_display_control();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 124,
		XV_Y, 156,
		XV_WIDTH, 112,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Display Control",
		PANEL_NOTIFY_PROC, map_display_control,
		NULL);
	return obj;
}

/*
 * Create object `but_mask' in the specified instance.

 */
Xv_opaque
segal_win_but_mask_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_mask_control();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 244,
		XV_Y, 156,
		XV_WIDTH, 98,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Mask Control",
		PANEL_NOTIFY_PROC, map_mask_control,
		NULL);
	return obj;
}

/*
 * Create object `but_bp' in the specified instance.

 */
Xv_opaque
segal_win_but_bp_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_bp();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 368,
		XV_Y, 156,
		XV_WIDTH, 78,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "BP's Tools",
		PANEL_NOTIFY_PROC, map_bp,
		NULL);
	return obj;
}

/*
 * Create object `msg_hint' in the specified instance.

 */
Xv_opaque
segal_win_msg_hint_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 184,
		XV_WIDTH, 32,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Hint:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `stats_win'.
 */
segal_stats_win_objects *
segal_stats_win_objects_initialize(ip, owner)
	segal_stats_win_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (segal_stats_win_objects *) calloc(1, sizeof (segal_stats_win_objects))))
		return (segal_stats_win_objects *) NULL;
	if (!ip->stats_win)
		ip->stats_win = segal_stats_win_stats_win_create(ip, owner);
	if (!ip->stat_control)
		ip->stat_control = segal_stats_win_stat_control_create(ip, ip->stats_win);
	if (!ip->stat_mess0)
		ip->stat_mess0 = segal_stats_win_stat_mess0_create(ip, ip->stat_control);
	if (!ip->stat_mess1)
		ip->stat_mess1 = segal_stats_win_stat_mess1_create(ip, ip->stat_control);
	if (!ip->stat_mess2)
		ip->stat_mess2 = segal_stats_win_stat_mess2_create(ip, ip->stat_control);
	if (!ip->stat_mess3)
		ip->stat_mess3 = segal_stats_win_stat_mess3_create(ip, ip->stat_control);
	if (!ip->stat_mess4)
		ip->stat_mess4 = segal_stats_win_stat_mess4_create(ip, ip->stat_control);
	if (!ip->stat_mess5)
		ip->stat_mess5 = segal_stats_win_stat_mess5_create(ip, ip->stat_control);
	if (!ip->stat_mess6)
		ip->stat_mess6 = segal_stats_win_stat_mess6_create(ip, ip->stat_control);
	if (!ip->stat_close)
		ip->stat_close = segal_stats_win_stat_close_create(ip, ip->stat_control);
	return ip;
}

/*
 * Create object `stats_win' in the specified instance.

 */
Xv_opaque
segal_stats_win_stats_win_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 330,
		XV_HEIGHT, 202,
		XV_LABEL, "Object Statistics",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `stat_control' in the specified instance.

 */
Xv_opaque
segal_stats_win_stat_control_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `stat_mess0' in the specified instance.

 */
Xv_opaque
segal_stats_win_stat_mess0_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 44,
		XV_Y, 8,
		XV_WIDTH, 107,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Object location:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `stat_mess1' in the specified instance.

 */
Xv_opaque
segal_stats_win_stat_mess1_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 15,
		XV_Y, 32,
		XV_WIDTH, 87,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Size (pixels):",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `stat_mess2' in the specified instance.

 */
Xv_opaque
segal_stats_win_stat_mess2_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 15,
		XV_Y, 56,
		XV_WIDTH, 104,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Total Intensity:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `stat_mess3' in the specified instance.

 */
Xv_opaque
segal_stats_win_stat_mess3_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 15,
		XV_Y, 80,
		XV_WIDTH, 166,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Average pixel intensity: ",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `stat_mess4' in the specified instance.

 */
Xv_opaque
segal_stats_win_stat_mess4_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 15,
		XV_Y, 104,
		XV_WIDTH, 102,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Perimeter size:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `stat_mess5' in the specified instance.

 */
Xv_opaque
segal_stats_win_stat_mess5_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 15,
		XV_Y, 128,
		XV_WIDTH, 112,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Min:  NN Max NN",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `stat_mess6' in the specified instance.

 */
Xv_opaque
segal_stats_win_stat_mess6_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 15,
		XV_Y, 152,
		XV_WIDTH, 53,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Median:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `stat_close' in the specified instance.

 */
Xv_opaque
segal_stats_win_stat_close_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		stat_close_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 140,
		XV_Y, 176,
		XV_WIDTH, 51,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Close",
		PANEL_NOTIFY_PROC, stat_close_proc,
		NULL);
	return obj;
}

