/*
 * surf_fit_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `surf_fit.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/icon_load.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "surf_fit_ui.h"

/*
 * Initialize an instance of object `win'.
 */
surf_fit_win_objects *
surf_fit_win_objects_initialize(ip, owner)
	surf_fit_win_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (surf_fit_win_objects *) calloc(1, sizeof (surf_fit_win_objects))))
		return (surf_fit_win_objects *) NULL;
	if (!ip->win)
		ip->win = surf_fit_win_win_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = surf_fit_win_controls1_create(ip, ip->win);
	if (!ip->set_alpha)
		ip->set_alpha = surf_fit_win_set_alpha_create(ip, ip->controls1);
	if (!ip->set_k)
		ip->set_k = surf_fit_win_set_k_create(ip, ip->controls1);
	if (!ip->set_iterations)
		ip->set_iterations = surf_fit_win_set_iterations_create(ip, ip->controls1);
	if (!ip->but_do_fitting)
		ip->but_do_fitting = surf_fit_win_but_do_fitting_create(ip, ip->controls1);
	if (!ip->but_close)
		ip->but_close = surf_fit_win_but_close_create(ip, ip->controls1);
	return ip;
}

/*
 * Create object `win' in the specified instance.

 */
Xv_opaque
surf_fit_win_win_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 283,
		XV_HEIGHT, 132,
		XV_LABEL, "Segal: Surface Fitting",
		FRAME_CLOSED, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.

 */
Xv_opaque
surf_fit_win_controls1_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `set_alpha' in the specified instance.

 */
Xv_opaque
surf_fit_win_set_alpha_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_surf_fit_alpha_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 32,
		XV_Y, 16,
		XV_WIDTH, 149,
		XV_HEIGHT, 20,
		PANEL_VALUE_X, 83,
		PANEL_VALUE_Y, 16,
		PANEL_SLIDER_WIDTH, 10,
		PANEL_LABEL_STRING, "Alpha:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 10,
		PANEL_TICKS, 0,
		PANEL_NOTIFY_PROC, set_surf_fit_alpha_proc,
		NULL);
	return obj;
}

/*
 * Create object `set_k' in the specified instance.

 */
Xv_opaque
surf_fit_win_set_k_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern Panel_setting	set_surf_fit_k_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 62,
		XV_Y, 36,
		XV_WIDTH, 60,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "K:",
		PANEL_VALUE_X, 82,
		PANEL_VALUE_Y, 36,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 5,
		PANEL_VALUE_STORED_LENGTH, 32,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, set_surf_fit_k_proc,
		NULL);
	return obj;
}

/*
 * Create object `set_iterations' in the specified instance.

 */
Xv_opaque
surf_fit_win_set_iterations_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_surf_fit_iterations_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 4,
		XV_Y, 56,
		XV_WIDTH, 274,
		XV_HEIGHT, 20,
		PANEL_VALUE_X, 82,
		PANEL_VALUE_Y, 56,
		PANEL_SLIDER_WIDTH, 100,
		PANEL_LABEL_STRING, "Iterations:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 100,
		PANEL_TICKS, 0,
		PANEL_NOTIFY_PROC, set_surf_fit_iterations_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_do_fitting' in the specified instance.

 */
Xv_opaque
surf_fit_win_but_do_fitting_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		surf_fit_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 80,
		XV_WIDTH, 78,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Do Fitting",
		PANEL_NOTIFY_PROC, surf_fit_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_close' in the specified instance.

 */
Xv_opaque
surf_fit_win_but_close_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_surf_fit();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 116,
		XV_Y, 104,
		XV_WIDTH, 51,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Close",
		PANEL_NOTIFY_PROC, map_surf_fit,
		NULL);
	return obj;
}

