#ifndef	view_HEADER
#define	view_HEADER

/*
 * view_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `view.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	win;
	Xv_opaque	canvas;
} view_win_objects;

extern view_win_objects	*view_win_objects_initialize();

extern Xv_opaque	view_win_win_create();
extern Xv_opaque	view_win_canvas_create();
#endif
