#
# makefile for user-contributed/lbl/xview/man
#

MANPAGES = genial.n segal.n xhist.n hview.n

install:	man-pgm

clean:	clean-pgm
clean-all:	clean_all

man:
	$(MANPRINT) $(MANPAGES)

doc:

pristine:	pristineman-pgm
