#
# makefile for directory drivers
#

# Subdirectories to make:

DIRS = nhips

# default action just makes src dirs

all: install

clean install pristine man doc: doit
	@for d in $(DIRS) ; do \
		( cd $$d ; echo make $@ on $(HERE)$$d ; make $(MFLAGS) $@ ) ; \
	done

doit:
