#ifndef	hview_HEADER
#define	hview_HEADER

/*
 * hview_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `hview.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	win;
	Xv_opaque	controls1;
	Xv_opaque	button2;
	Xv_opaque	slider1;
	Xv_opaque	button1;
	Xv_opaque	can;
} hview_win_objects;

extern hview_win_objects	*hview_win_objects_initialize();

extern Xv_opaque	hview_win_win_create();
extern Xv_opaque	hview_win_controls1_create();
extern Xv_opaque	hview_win_button2_create();
extern Xv_opaque	hview_win_slider1_create();
extern Xv_opaque	hview_win_button1_create();
extern Xv_opaque	hview_win_can_create();
#endif
