#
# makefile for directory user-contributed/lbl/hstream
#

DIRS = sources

# default action just makes src dirs

all: install
  
clean clean-all install pristine man doc: doit
	@for d in $(DIRS) ; do \
		( cd $$d ; echo make $@ on $(HERE)$$d ;	\
			make CCS_ROOT=$(TOPDIR)/$(HERE)/.. $(MFLAGS) $@ ) ; \
	done
	@if [ "$@" = "clean-all" ];	then	\
		rm -f Makefile;	else	true;	fi

doit:

