#ifndef	comment_HEADER
#define	comment_HEADER

/*
 * comment_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `comment.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	comm_win;
	Xv_opaque	textpane1;
} comment_comm_win_objects;

extern comment_comm_win_objects	*comment_comm_win_objects_initialize();

extern Xv_opaque	comment_comm_win_comm_win_create();
extern Xv_opaque	comment_comm_win_textpane1_create();
#endif
