#ifndef	histo_HEADER
#define	histo_HEADER

/*
 * histo_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `histo.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	histo_ctrl;
	Xv_opaque	controls1;
	Xv_opaque	histno;
	Xv_opaque	clear_all;
	Xv_opaque	message3;
	Xv_opaque	message4;
	Xv_opaque	min1;
	Xv_opaque	pnt1;
	Xv_opaque	sel1;
	Xv_opaque	max1;
	Xv_opaque	pnt2;
	Xv_opaque	sel2;
	Xv_opaque	min2;
	Xv_opaque	max2;
	Xv_opaque	pnt3;
	Xv_opaque	sel3;
	Xv_opaque	min3;
	Xv_opaque	max3;
	Xv_opaque	pnt4;
	Xv_opaque	sel4;
	Xv_opaque	min4;
	Xv_opaque	max4;
	Xv_opaque	pnt5;
	Xv_opaque	sel5;
	Xv_opaque	min5;
	Xv_opaque	max5;
	Xv_opaque	pnt6;
	Xv_opaque	sel6;
	Xv_opaque	min6;
	Xv_opaque	max6;
	Xv_opaque	pnt7;
	Xv_opaque	sel7;
	Xv_opaque	min7;
	Xv_opaque	max7;
	Xv_opaque	pnt8;
	Xv_opaque	sel8;
	Xv_opaque	min8;
	Xv_opaque	max8;
	Xv_opaque	palcanv;
} histo_histo_ctrl_objects;

extern histo_histo_ctrl_objects	*histo_histo_ctrl_objects_initialize();

extern Xv_opaque	histo_histo_ctrl_histo_ctrl_create();
extern Xv_opaque	histo_histo_ctrl_controls1_create();
extern Xv_opaque	histo_histo_ctrl_histno_create();
extern Xv_opaque	histo_histo_ctrl_clear_all_create();
extern Xv_opaque	histo_histo_ctrl_message3_create();
extern Xv_opaque	histo_histo_ctrl_message4_create();
extern Xv_opaque	histo_histo_ctrl_min1_create();
extern Xv_opaque	histo_histo_ctrl_pnt1_create();
extern Xv_opaque	histo_histo_ctrl_sel1_create();
extern Xv_opaque	histo_histo_ctrl_max1_create();
extern Xv_opaque	histo_histo_ctrl_pnt2_create();
extern Xv_opaque	histo_histo_ctrl_sel2_create();
extern Xv_opaque	histo_histo_ctrl_min2_create();
extern Xv_opaque	histo_histo_ctrl_max2_create();
extern Xv_opaque	histo_histo_ctrl_pnt3_create();
extern Xv_opaque	histo_histo_ctrl_sel3_create();
extern Xv_opaque	histo_histo_ctrl_min3_create();
extern Xv_opaque	histo_histo_ctrl_max3_create();
extern Xv_opaque	histo_histo_ctrl_pnt4_create();
extern Xv_opaque	histo_histo_ctrl_sel4_create();
extern Xv_opaque	histo_histo_ctrl_min4_create();
extern Xv_opaque	histo_histo_ctrl_max4_create();
extern Xv_opaque	histo_histo_ctrl_pnt5_create();
extern Xv_opaque	histo_histo_ctrl_sel5_create();
extern Xv_opaque	histo_histo_ctrl_min5_create();
extern Xv_opaque	histo_histo_ctrl_max5_create();
extern Xv_opaque	histo_histo_ctrl_pnt6_create();
extern Xv_opaque	histo_histo_ctrl_sel6_create();
extern Xv_opaque	histo_histo_ctrl_min6_create();
extern Xv_opaque	histo_histo_ctrl_max6_create();
extern Xv_opaque	histo_histo_ctrl_pnt7_create();
extern Xv_opaque	histo_histo_ctrl_sel7_create();
extern Xv_opaque	histo_histo_ctrl_min7_create();
extern Xv_opaque	histo_histo_ctrl_max7_create();
extern Xv_opaque	histo_histo_ctrl_pnt8_create();
extern Xv_opaque	histo_histo_ctrl_sel8_create();
extern Xv_opaque	histo_histo_ctrl_min8_create();
extern Xv_opaque	histo_histo_ctrl_max8_create();
extern Xv_opaque	histo_histo_ctrl_palcanv_create();

typedef struct {
	Xv_opaque	display;
	Xv_opaque	controls2;
	Xv_opaque	message1;
	Xv_opaque	color_histo;
	Xv_opaque	refresh;
	Xv_opaque	message2;
	Xv_opaque	magnify;
	Xv_opaque	unmagnify;
	Xv_opaque	restore;
	Xv_opaque	message5;
	Xv_opaque	histocanv;
} histo_display_objects;

extern histo_display_objects	*histo_display_objects_initialize();

extern Xv_opaque	histo_display_display_create();
extern Xv_opaque	histo_display_controls2_create();
extern Xv_opaque	histo_display_message1_create();
extern Xv_opaque	histo_display_color_histo_create();
extern Xv_opaque	histo_display_refresh_create();
extern Xv_opaque	histo_display_message2_create();
extern Xv_opaque	histo_display_magnify_create();
extern Xv_opaque	histo_display_unmagnify_create();
extern Xv_opaque	histo_display_restore_create();
extern Xv_opaque	histo_display_message5_create();
extern Xv_opaque	histo_display_histocanv_create();
#endif
