/*
 * hview_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `hview.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "hview_ui.h"

void	gamma_proc();

/*
 * Global object definitions.
 */
hview_win_objects	*Hview_win;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(argc, argv)
	int	argc;
	char	**argv;
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Hview_win = hview_win_objects_initialize(NULL, NULL);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Hview_win->win);
	exit(0);
}

#endif


/*
 * Notify callback function for `button2'.
 */
void
make_perfect_colors(item, event)
	Panel_item	item;
	Event		*event;
{
	hview_win_objects *ip = (hview_win_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("hview: make_perfect_colors\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `slider1'.
 */
void
hview_win_slider1_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	hview_win_objects *ip = (hview_win_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "hview: hview_win_slider1_notify_callback: value: %d\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	gamma_proc(item, value, event);
	
	/* gxv_end_connections */

}

/*
 * User-defined action for `slider1'.
 */
void
gamma_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	fputs("hview: gamma_proc\n", stderr);
}

/*
 * Notify callback function for `button1'.
 */
void
quit_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	hview_win_objects *ip = (hview_win_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("hview: quit_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Repaint callback function for `can'.
 */
void
canvas_repaint_proc(canvas, paint_window, display, xid, rects)
	Canvas		canvas;
	Xv_window	paint_window;
	Display		*display;
	Window		xid;
	Xv_xrectlist	*rects;
{
	fputs("hview: canvas_repaint_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}
