/*
 * frame_control_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `frame_control.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/icon_load.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "frame_control_ui.h"

/*
 * Initialize an instance of object `win'.
 */
frame_control_win_objects *
frame_control_win_objects_initialize(ip, owner)
	frame_control_win_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (frame_control_win_objects *) calloc(1, sizeof (frame_control_win_objects))))
		return (frame_control_win_objects *) NULL;
	if (!ip->win)
		ip->win = frame_control_win_win_create(ip, owner);
	if (!ip->controls_fill1)
		ip->controls_fill1 = frame_control_win_controls_fill1_create(ip, ip->win);
	if (!ip->msg_image)
		ip->msg_image = frame_control_win_msg_image_create(ip, ip->controls_fill1);
	if (!ip->canv_image_frame_status)
		ip->canv_image_frame_status = frame_control_win_canv_image_frame_status_create(ip, ip->win);
	if (!ip->controls_fill2)
		ip->controls_fill2 = frame_control_win_controls_fill2_create(ip, ip->win);
	if (!ip->msg_mask)
		ip->msg_mask = frame_control_win_msg_mask_create(ip, ip->controls_fill2);
	if (!ip->canv_mask_frame_status)
		ip->canv_mask_frame_status = frame_control_win_canv_mask_frame_status_create(ip, ip->win);
	if (!ip->controls)
		ip->controls = frame_control_win_controls_create(ip, ip->win);
	if (!ip->curr_frame)
		ip->curr_frame = frame_control_win_curr_frame_create(ip, ip->controls);
	if (!ip->msg_frame_status)
		ip->msg_frame_status = frame_control_win_msg_frame_status_create(ip, ip->controls);
	if (!ip->set_image_frame_status)
		ip->set_image_frame_status = frame_control_win_set_image_frame_status_create(ip, ip->controls);
	if (!ip->text_ref_frame)
		ip->text_ref_frame = frame_control_win_text_ref_frame_create(ip, ip->controls);
	if (!ip->set_mask_frame_status)
		ip->set_mask_frame_status = frame_control_win_set_mask_frame_status_create(ip, ip->controls);
	if (!ip->movie_go_button)
		ip->movie_go_button = frame_control_win_movie_go_button_create(ip, ip->controls);
	if (!ip->but_movie_stop)
		ip->but_movie_stop = frame_control_win_but_movie_stop_create(ip, ip->controls);
	if (!ip->movie_beg_frame)
		ip->movie_beg_frame = frame_control_win_movie_beg_frame_create(ip, ip->controls);
	if (!ip->movie_end_frame)
		ip->movie_end_frame = frame_control_win_movie_end_frame_create(ip, ip->controls);
	if (!ip->set_stack_load)
		ip->set_stack_load = frame_control_win_set_stack_load_create(ip, ip->controls);
	if (!ip->but_close)
		ip->but_close = frame_control_win_but_close_create(ip, ip->controls);
	return ip;
}

/*
 * Create object `win' in the specified instance.

 */
Xv_opaque
frame_control_win_win_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 458,
		XV_HEIGHT, 239,
		XV_LABEL, "Segal : Frame Control",
		FRAME_CLOSED, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls_fill1' in the specified instance.

 */
Xv_opaque
frame_control_win_controls_fill1_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, 176,
		XV_HEIGHT, 26,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `msg_image' in the specified instance.

 */
Xv_opaque
frame_control_win_msg_image_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 124,
		XV_Y, 8,
		XV_WIDTH, 45,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Image:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `canv_image_frame_status' in the specified instance.

 */
Xv_opaque
frame_control_win_canv_image_frame_status_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 176,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 28,
		NULL);
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

/*
 * Create object `controls_fill2' in the specified instance.

 */
Xv_opaque
frame_control_win_controls_fill2_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 26,
		XV_WIDTH, 176,
		XV_HEIGHT, 26,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `msg_mask' in the specified instance.

 */
Xv_opaque
frame_control_win_msg_mask_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 128,
		XV_Y, 8,
		XV_WIDTH, 39,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Mask:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `canv_mask_frame_status' in the specified instance.

 */
Xv_opaque
frame_control_win_canv_mask_frame_status_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 176,
		XV_Y, 26,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 26,
		NULL);
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

/*
 * Create object `controls' in the specified instance.

 */
Xv_opaque
frame_control_win_controls_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 52,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `curr_frame' in the specified instance.

 */
Xv_opaque
frame_control_win_curr_frame_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		get_frame_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		XV_WIDTH, 443,
		XV_HEIGHT, 20,
		PANEL_VALUE_X, 118,
		PANEL_VALUE_Y, 8,
		PANEL_SLIDER_WIDTH, 255,
		PANEL_LABEL_STRING, "Current Frame:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, TRUE,
		PANEL_SHOW_RANGE, FALSE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 1,
		PANEL_MAX_VALUE, 256,
		PANEL_TICKS, 0,
		PANEL_NOTIFY_PROC, get_frame_proc,
		NULL);
	return obj;
}

/*
 * Create object `msg_frame_status' in the specified instance.

 */
Xv_opaque
frame_control_win_msg_frame_status_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 28,
		XV_WIDTH, 89,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Frame Status",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `set_image_frame_status' in the specified instance.

 */
Xv_opaque
frame_control_win_set_image_frame_status_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_image_frame_status_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 36,
		XV_Y, 44,
		XV_WIDTH, 227,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 89,
		PANEL_VALUE_Y, 44,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Image:",
		PANEL_NOTIFY_PROC, set_image_frame_status_proc,
		PANEL_CHOICE_STRINGS,
			"Unregistered",
			"Registered",
			0,
		NULL);
	return obj;
}

/*
 * Create object `text_ref_frame' in the specified instance.

 */
Xv_opaque
frame_control_win_text_ref_frame_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern Panel_setting	set_ref_frame_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 276,
		XV_Y, 52,
		XV_WIDTH, 162,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "Reference Frame:",
		PANEL_VALUE_X, 402,
		PANEL_VALUE_Y, 52,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 4,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, set_ref_frame_proc,
		NULL);
	return obj;
}

/*
 * Create object `set_mask_frame_status' in the specified instance.

 */
Xv_opaque
frame_control_win_set_mask_frame_status_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_mask_frame_status_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 44,
		XV_Y, 72,
		XV_WIDTH, 265,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 91,
		PANEL_VALUE_Y, 72,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Mask:",
		PANEL_NOTIFY_PROC, set_mask_frame_status_proc,
		PANEL_CHOICE_STRINGS,
			"Blank",
			"Altered",
			"Saved",
			"Locked",
			0,
		NULL);
	return obj;
}

/*
 * Create object `movie_go_button' in the specified instance.

 */
Xv_opaque
frame_control_win_movie_go_button_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		movie_go_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 344,
		XV_Y, 112,
		XV_WIDTH, 47,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Start",
		PANEL_NOTIFY_PROC, movie_go_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_movie_stop' in the specified instance.

 */
Xv_opaque
frame_control_win_but_movie_stop_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 402,
		XV_Y, 112,
		XV_WIDTH, 45,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Stop",
		NULL);
	return obj;
}

/*
 * Create object `movie_beg_frame' in the specified instance.

 */
Xv_opaque
frame_control_win_movie_beg_frame_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 26,
		XV_Y, 116,
		XV_WIDTH, 154,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "Movie From:",
		PANEL_VALUE_X, 116,
		PANEL_VALUE_Y, 116,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `movie_end_frame' in the specified instance.

 */
Xv_opaque
frame_control_win_movie_end_frame_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 208,
		XV_Y, 116,
		XV_WIDTH, 92,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "To:",
		PANEL_VALUE_X, 236,
		PANEL_VALUE_Y, 116,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `set_stack_load' in the specified instance.

 */
Xv_opaque
frame_control_win_set_stack_load_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 136,
		XV_WIDTH, 162,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 117,
		PANEL_VALUE_Y, 136,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Stack Loading:",
		PANEL_CHOICE_STRINGS,
			"Yes",
			"No",
			0,
		NULL);
	return obj;
}

/*
 * Create object `but_close' in the specified instance.

 */
Xv_opaque
frame_control_win_but_close_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_frame_control();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 208,
		XV_Y, 164,
		XV_WIDTH, 51,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Close",
		PANEL_NOTIFY_PROC, map_frame_control,
		NULL);
	return obj;
}

