/*
 * load_save_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `load_save.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/icon_load.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "load_save_ui.h"

/*
 * Initialize an instance of object `pop_load'.
 */
load_save_pop_load_objects *
load_save_pop_load_objects_initialize(ip, owner)
	load_save_pop_load_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (load_save_pop_load_objects *) calloc(1, sizeof (load_save_pop_load_objects))))
		return (load_save_pop_load_objects *) NULL;
	if (!ip->pop_load)
		ip->pop_load = load_save_pop_load_pop_load_create(ip, owner);
	if (!ip->controls_load)
		ip->controls_load = load_save_pop_load_controls_load_create(ip, ip->pop_load);
	if (!ip->load_which)
		ip->load_which = load_save_pop_load_load_which_create(ip, ip->controls_load);
	if (!ip->load_dname)
		ip->load_dname = load_save_pop_load_load_dname_create(ip, ip->controls_load);
	if (!ip->load_fname)
		ip->load_fname = load_save_pop_load_load_fname_create(ip, ip->controls_load);
	if (!ip->but_load)
		ip->but_load = load_save_pop_load_but_load_create(ip, ip->controls_load);
	return ip;
}

/*
 * Create object `pop_load' in the specified instance.

 */
Xv_opaque
load_save_pop_load_pop_load_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 413,
		XV_HEIGHT, 126,
		XV_LABEL, "Segal : Load",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls_load' in the specified instance.

 */
Xv_opaque
load_save_pop_load_controls_load_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `load_which' in the specified instance.

 */
Xv_opaque
load_save_pop_load_load_which_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		set_load_which();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 44,
		XV_Y, 8,
		XV_WIDTH, 180,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 87,
		PANEL_VALUE_Y, 8,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Load:",
		PANEL_NOTIFY_PROC, set_load_which,
		PANEL_CHOICE_STRINGS,
			"Image",
			"Mask",
			"List",
			0,
		NULL);
	return obj;
}

/*
 * Create object `load_dname' in the specified instance.

 */
Xv_opaque
load_save_pop_load_load_dname_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 44,
		XV_WIDTH, 394,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "Directory:",
		PANEL_VALUE_X, 87,
		PANEL_VALUE_Y, 44,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 100,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `load_fname' in the specified instance.

 */
Xv_opaque
load_save_pop_load_load_fname_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 76,
		XV_WIDTH, 394,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "Filename:",
		PANEL_VALUE_X, 87,
		PANEL_VALUE_Y, 76,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 100,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `but_load' in the specified instance.

 */
Xv_opaque
load_save_pop_load_but_load_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		but_load_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 200,
		XV_Y, 104,
		XV_WIDTH, 46,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Load",
		PANEL_NOTIFY_PROC, but_load_proc,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `pop_create'.
 */
load_save_pop_create_objects *
load_save_pop_create_objects_initialize(ip, owner)
	load_save_pop_create_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (load_save_pop_create_objects *) calloc(1, sizeof (load_save_pop_create_objects))))
		return (load_save_pop_create_objects *) NULL;
	if (!ip->pop_create)
		ip->pop_create = load_save_pop_create_pop_create_create(ip, owner);
	if (!ip->controls_create)
		ip->controls_create = load_save_pop_create_controls_create_create(ip, ip->pop_create);
	if (!ip->create_dname)
		ip->create_dname = load_save_pop_create_create_dname_create(ip, ip->controls_create);
	if (!ip->create_fname)
		ip->create_fname = load_save_pop_create_create_fname_create(ip, ip->controls_create);
	if (!ip->but_create)
		ip->but_create = load_save_pop_create_but_create_create(ip, ip->controls_create);
	return ip;
}

/*
 * Create object `pop_create' in the specified instance.

 */
Xv_opaque
load_save_pop_create_pop_create_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 418,
		XV_HEIGHT, 93,
		XV_LABEL, "Segal : Create Mask",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls_create' in the specified instance.

 */
Xv_opaque
load_save_pop_create_controls_create_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `create_dname' in the specified instance.

 */
Xv_opaque
load_save_pop_create_create_dname_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 12,
		XV_WIDTH, 394,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "Directory:",
		PANEL_VALUE_X, 91,
		PANEL_VALUE_Y, 12,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 100,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `create_fname' in the specified instance.

 */
Xv_opaque
load_save_pop_create_create_fname_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 44,
		XV_WIDTH, 394,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "Filename:",
		PANEL_VALUE_X, 91,
		PANEL_VALUE_Y, 44,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 100,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `but_create' in the specified instance.

 */
Xv_opaque
load_save_pop_create_but_create_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		but_create_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 192,
		XV_Y, 72,
		XV_WIDTH, 58,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Create",
		PANEL_NOTIFY_PROC, but_create_proc,
		NULL);
	return obj;
}

