#ifndef	segal_HEADER
#define	segal_HEADER

/*
 * segal_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `segal.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;

extern Xv_opaque	segal_menu_file_create();

typedef struct {
	Xv_opaque	win;
	Xv_opaque	controls;
	Xv_opaque	but_file;
	Xv_opaque	msg_image_fname;
	Xv_opaque	msg_image_size;
	Xv_opaque	msg_mask_fname;
	Xv_opaque	but_undo;
	Xv_opaque	msg_pixedit;
	Xv_opaque	msg_pixel_value;
	Xv_opaque	but_original;
	Xv_opaque	but_edit;
	Xv_opaque	but_mask_log;
	Xv_opaque	but_image_reg;
	Xv_opaque	but_filter;
	Xv_opaque	but_frame;
	Xv_opaque	but_display;
	Xv_opaque	but_mask;
	Xv_opaque	but_bp;
	Xv_opaque	msg_hint;
} segal_win_objects;

extern segal_win_objects	*segal_win_objects_initialize();

extern Xv_opaque	segal_win_win_create();
extern Xv_opaque	segal_win_controls_create();
extern Xv_opaque	segal_win_but_file_create();
extern Xv_opaque	segal_win_msg_image_fname_create();
extern Xv_opaque	segal_win_msg_image_size_create();
extern Xv_opaque	segal_win_msg_mask_fname_create();
extern Xv_opaque	segal_win_but_undo_create();
extern Xv_opaque	segal_win_msg_pixedit_create();
extern Xv_opaque	segal_win_msg_pixel_value_create();
extern Xv_opaque	segal_win_but_original_create();
extern Xv_opaque	segal_win_but_edit_create();
extern Xv_opaque	segal_win_but_mask_log_create();
extern Xv_opaque	segal_win_but_image_reg_create();
extern Xv_opaque	segal_win_but_filter_create();
extern Xv_opaque	segal_win_but_frame_create();
extern Xv_opaque	segal_win_but_display_create();
extern Xv_opaque	segal_win_but_mask_create();
extern Xv_opaque	segal_win_but_bp_create();
extern Xv_opaque	segal_win_msg_hint_create();

typedef struct {
	Xv_opaque	stats_win;
	Xv_opaque	stat_control;
	Xv_opaque	stat_mess0;
	Xv_opaque	stat_mess1;
	Xv_opaque	stat_mess2;
	Xv_opaque	stat_mess3;
	Xv_opaque	stat_mess4;
	Xv_opaque	stat_mess5;
	Xv_opaque	stat_mess6;
	Xv_opaque	stat_close;
} segal_stats_win_objects;

extern segal_stats_win_objects	*segal_stats_win_objects_initialize();

extern Xv_opaque	segal_stats_win_stats_win_create();
extern Xv_opaque	segal_stats_win_stat_control_create();
extern Xv_opaque	segal_stats_win_stat_mess0_create();
extern Xv_opaque	segal_stats_win_stat_mess1_create();
extern Xv_opaque	segal_stats_win_stat_mess2_create();
extern Xv_opaque	segal_stats_win_stat_mess3_create();
extern Xv_opaque	segal_stats_win_stat_mess4_create();
extern Xv_opaque	segal_stats_win_stat_mess5_create();
extern Xv_opaque	segal_stats_win_stat_mess6_create();
extern Xv_opaque	segal_stats_win_stat_close_create();
#endif
