/*
 * genial.c - Contains main() for project genial
 * This file was generated by `gxv'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "comment_ui.h"
#include "display_ui.h"
#include "file_ui.h"
#include "main_control_ui.h"
#include "gfm_ui.h"
#include "histo_ui.h"
#include "trace_ui.h"
#include "zoom_ui.h"


/*
 * External variable declarations.
 */
comment_comm_win_objects	*Comment_comm_win;
file_window1_objects	*File_window1;
file_rect_choice_win_objects	*File_rect_choice_win;
main_control_ctrlwin_objects	*Main_control_ctrlwin;
main_control_imgwin_objects	*Main_control_imgwin;
histo_display_objects	*Histo_display;
display_ctrlwin_objects	*Display_ctrlwin;
gfm_popup_objects	*Gfm_popup;
histo_histo_ctrl_objects	*Histo_histo_ctrl;
trace_tcntrl_objects	*Trace_tcntrl;
trace_trwin_objects	*Trace_trwin;
trace_intgwin_objects	*Trace_intgwin;
zoom_zmwin_objects	*Zoom_zmwin;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

/*
 * main for project genial
 */
void
main(argc, argv)
	int		argc;
	char		**argv;
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Histo_display = histo_display_objects_initialize(NULL, NULL);
	File_window1 = file_window1_objects_initialize(NULL, NULL);
	File_rect_choice_win = file_rect_choice_win_objects_initialize(NULL, File_window1->window1);
	Main_control_ctrlwin = main_control_ctrlwin_objects_initialize(NULL, NULL);
	Main_control_imgwin = main_control_imgwin_objects_initialize(NULL, NULL);
	Zoom_zmwin = zoom_zmwin_objects_initialize(NULL, NULL);
	Trace_tcntrl = trace_tcntrl_objects_initialize(NULL, NULL);
	Trace_trwin = trace_trwin_objects_initialize(NULL, NULL);
	Trace_intgwin = trace_intgwin_objects_initialize(NULL, NULL);
	Display_ctrlwin = display_ctrlwin_objects_initialize(NULL, NULL);
	Histo_histo_ctrl = histo_histo_ctrl_objects_initialize(NULL, NULL);
	Comment_comm_win = comment_comm_win_objects_initialize(NULL, NULL);
	Gfm_popup = gfm_popup_objects_initialize(NULL, NULL);
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Histo_display->display);
	exit(0);
}

#endif

