#ifndef	zoom_HEADER
#define	zoom_HEADER

/*
 * zoom_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `zoom.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	zmwin;
	Xv_opaque	zmcanv;
} zoom_zmwin_objects;

extern zoom_zmwin_objects	*zoom_zmwin_objects_initialize();

extern Xv_opaque	zoom_zmwin_zmwin_create();
extern Xv_opaque	zoom_zmwin_zmcanv_create();
#endif
