/*
 * display_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `display.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "display_ui.h"
#include "gen.h"
#include "genial.h"


/*
 * Global object definitions.
 */
display_ctrlwin_objects	*Display_ctrlwin;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(argc, argv)
	int	argc;
	char	**argv;
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Display_ctrlwin = display_ctrlwin_objects_initialize(NULL, NULL);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Display_ctrlwin->ctrlwin);
	exit(0);
}

#endif


/*
 * Notify callback function for `gamma'.
 */
void
gamma_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	display_ctrlwin_objects *ip = (display_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "display: gamma_proc: value: %d\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `cmap_min'.
 */
Panel_setting
cm_min_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	display_ctrlwin_objects *ip = (display_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	int	value = (int) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "display: cm_min_proc: value: %d\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `cmap_max'.
 */
Panel_setting
cm_max_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	display_ctrlwin_objects *ip = (display_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	int	value = (int) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "display: cm_max_proc: value: %d\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `shrink_fac'.
 */
void
shrink_proc(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	display_ctrlwin_objects *ip = (display_ctrlwin_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "display: shrink_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}
