/*
 * histo_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `histo.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "histo_ui.h"

/*
 * Initialize an instance of object `histo_ctrl'.
 */
histo_histo_ctrl_objects *
histo_histo_ctrl_objects_initialize(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (histo_histo_ctrl_objects *) calloc(1, sizeof (histo_histo_ctrl_objects))))
		return (histo_histo_ctrl_objects *) NULL;
	if (!ip->histo_ctrl)
		ip->histo_ctrl = histo_histo_ctrl_histo_ctrl_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = histo_histo_ctrl_controls1_create(ip, ip->histo_ctrl);
	if (!ip->histno)
		ip->histno = histo_histo_ctrl_histno_create(ip, ip->controls1);
	if (!ip->clear_all)
		ip->clear_all = histo_histo_ctrl_clear_all_create(ip, ip->controls1);
	if (!ip->message3)
		ip->message3 = histo_histo_ctrl_message3_create(ip, ip->controls1);
	if (!ip->message4)
		ip->message4 = histo_histo_ctrl_message4_create(ip, ip->controls1);
	if (!ip->min1)
		ip->min1 = histo_histo_ctrl_min1_create(ip, ip->controls1);
	if (!ip->pnt1)
		ip->pnt1 = histo_histo_ctrl_pnt1_create(ip, ip->controls1);
	if (!ip->sel1)
		ip->sel1 = histo_histo_ctrl_sel1_create(ip, ip->controls1);
	if (!ip->max1)
		ip->max1 = histo_histo_ctrl_max1_create(ip, ip->controls1);
	if (!ip->pnt2)
		ip->pnt2 = histo_histo_ctrl_pnt2_create(ip, ip->controls1);
	if (!ip->sel2)
		ip->sel2 = histo_histo_ctrl_sel2_create(ip, ip->controls1);
	if (!ip->min2)
		ip->min2 = histo_histo_ctrl_min2_create(ip, ip->controls1);
	if (!ip->max2)
		ip->max2 = histo_histo_ctrl_max2_create(ip, ip->controls1);
	if (!ip->pnt3)
		ip->pnt3 = histo_histo_ctrl_pnt3_create(ip, ip->controls1);
	if (!ip->sel3)
		ip->sel3 = histo_histo_ctrl_sel3_create(ip, ip->controls1);
	if (!ip->min3)
		ip->min3 = histo_histo_ctrl_min3_create(ip, ip->controls1);
	if (!ip->max3)
		ip->max3 = histo_histo_ctrl_max3_create(ip, ip->controls1);
	if (!ip->pnt4)
		ip->pnt4 = histo_histo_ctrl_pnt4_create(ip, ip->controls1);
	if (!ip->sel4)
		ip->sel4 = histo_histo_ctrl_sel4_create(ip, ip->controls1);
	if (!ip->min4)
		ip->min4 = histo_histo_ctrl_min4_create(ip, ip->controls1);
	if (!ip->max4)
		ip->max4 = histo_histo_ctrl_max4_create(ip, ip->controls1);
	if (!ip->pnt5)
		ip->pnt5 = histo_histo_ctrl_pnt5_create(ip, ip->controls1);
	if (!ip->sel5)
		ip->sel5 = histo_histo_ctrl_sel5_create(ip, ip->controls1);
	if (!ip->min5)
		ip->min5 = histo_histo_ctrl_min5_create(ip, ip->controls1);
	if (!ip->max5)
		ip->max5 = histo_histo_ctrl_max5_create(ip, ip->controls1);
	if (!ip->pnt6)
		ip->pnt6 = histo_histo_ctrl_pnt6_create(ip, ip->controls1);
	if (!ip->sel6)
		ip->sel6 = histo_histo_ctrl_sel6_create(ip, ip->controls1);
	if (!ip->min6)
		ip->min6 = histo_histo_ctrl_min6_create(ip, ip->controls1);
	if (!ip->max6)
		ip->max6 = histo_histo_ctrl_max6_create(ip, ip->controls1);
	if (!ip->pnt7)
		ip->pnt7 = histo_histo_ctrl_pnt7_create(ip, ip->controls1);
	if (!ip->sel7)
		ip->sel7 = histo_histo_ctrl_sel7_create(ip, ip->controls1);
	if (!ip->min7)
		ip->min7 = histo_histo_ctrl_min7_create(ip, ip->controls1);
	if (!ip->max7)
		ip->max7 = histo_histo_ctrl_max7_create(ip, ip->controls1);
	if (!ip->pnt8)
		ip->pnt8 = histo_histo_ctrl_pnt8_create(ip, ip->controls1);
	if (!ip->sel8)
		ip->sel8 = histo_histo_ctrl_sel8_create(ip, ip->controls1);
	if (!ip->min8)
		ip->min8 = histo_histo_ctrl_min8_create(ip, ip->controls1);
	if (!ip->max8)
		ip->max8 = histo_histo_ctrl_max8_create(ip, ip->controls1);
	if (!ip->palcanv)
		ip->palcanv = histo_histo_ctrl_palcanv_create(ip, ip->histo_ctrl);
	return ip;
}

/*
 * Create object `histo_ctrl' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_histo_ctrl_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 311,
		XV_HEIGHT, 390,
		XV_LABEL, "Histogram Color Control",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_controls1_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `histno' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_histno_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	histno_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 4,
		XV_Y, 12,
		PANEL_VALUE_DISPLAY_LENGTH, 2,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Histogram:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, histno_proc,
		NULL);
	return obj;
}

/*
 * Create object `clear_all' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_clear_all_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		clear_histo_color_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 236,
		XV_Y, 12,
		PANEL_LABEL_STRING, "Clear All",
		PANEL_NOTIFY_PROC, clear_histo_color_proc,
		NULL);
	return obj;
}

/*
 * Create object `message3' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_message3_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 4,
		XV_Y, 40,
		PANEL_LABEL_STRING, "Paint",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message4' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_message4_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 100,
		XV_Y, 40,
		PANEL_LABEL_STRING, "Select",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `min1' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_min1_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval1_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 60,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Min:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval1_proc,
		NULL);
	return obj;
}

/*
 * Create object `pnt1' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_pnt1_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_paint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 64,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_NOTIFY_PROC, histo_color_paint_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `sel1' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_sel1_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_select_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 104,
		XV_Y, 64,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_NOTIFY_PROC, histo_color_select_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `max1' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_max1_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval1_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 76,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Max:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval1_proc,
		NULL);
	return obj;
}

/*
 * Create object `pnt2' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_pnt2_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_paint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 104,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_paint_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `sel2' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_sel2_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_select_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 104,
		XV_Y, 104,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_select_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `min2' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_min2_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval2_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 104,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Min:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval2_proc,
		NULL);
	return obj;
}

/*
 * Create object `max2' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_max2_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval2_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 120,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Max:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval2_proc,
		NULL);
	return obj;
}

/*
 * Create object `pnt3' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_pnt3_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_paint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 144,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_paint_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `sel3' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_sel3_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_select_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 104,
		XV_Y, 144,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_select_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `min3' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_min3_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval3_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 144,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Min:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval3_proc,
		NULL);
	return obj;
}

/*
 * Create object `max3' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_max3_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval3_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 160,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Max:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval3_proc,
		NULL);
	return obj;
}

/*
 * Create object `pnt4' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_pnt4_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_paint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 184,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_paint_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `sel4' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_sel4_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_select_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 104,
		XV_Y, 184,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_select_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `min4' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_min4_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval4_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 184,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Min:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval4_proc,
		NULL);
	return obj;
}

/*
 * Create object `max4' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_max4_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval4_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 200,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Max:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval4_proc,
		NULL);
	return obj;
}

/*
 * Create object `pnt5' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_pnt5_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_paint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 224,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_paint_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `sel5' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_sel5_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_select_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 104,
		XV_Y, 224,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_select_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `min5' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_min5_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval5_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 224,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Min:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval5_proc,
		NULL);
	return obj;
}

/*
 * Create object `max5' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_max5_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval5_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 240,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Max:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval5_proc,
		NULL);
	return obj;
}

/*
 * Create object `pnt6' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_pnt6_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_paint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 264,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_paint_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `sel6' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_sel6_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_select_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 104,
		XV_Y, 264,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_select_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `min6' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_min6_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval6_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 264,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Min:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval6_proc,
		NULL);
	return obj;
}

/*
 * Create object `max6' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_max6_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval6_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 280,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Max:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval6_proc,
		NULL);
	return obj;
}

/*
 * Create object `pnt7' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_pnt7_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_paint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 304,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_paint_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `sel7' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_sel7_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_select_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 104,
		XV_Y, 304,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_select_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `min7' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_min7_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval7_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 304,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Min:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval7_proc,
		NULL);
	return obj;
}

/*
 * Create object `max7' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_max7_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval7_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 320,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Max:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval7_proc,
		NULL);
	return obj;
}

/*
 * Create object `pnt8' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_pnt8_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_paint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 344,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_paint_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `sel8' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_sel8_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_select_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 104,
		XV_Y, 344,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_NOTIFY_PROC, histo_color_select_proc,
		PANEL_CHOICE_STRING, 0, "",
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `min8' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_min8_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval8_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 344,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Min:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval8_proc,
		NULL);
	return obj;
}

/*
 * Create object `max8' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_max8_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	interval8_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 156,
		XV_Y, 360,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Max:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100000000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, interval8_proc,
		NULL);
	return obj;
}

/*
 * Create object `palcanv' in the specified instance.
 */
Xv_opaque
histo_histo_ctrl_palcanv_create(ip, owner)
	histo_histo_ctrl_objects	*ip;
	Xv_opaque	owner;
{
	extern void	palcanv_repaint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 44,
		XV_Y, 58,
		XV_WIDTH, 43,
		XV_HEIGHT, 323,
		CANVAS_REPAINT_PROC, palcanv_repaint_proc,
		CANVAS_X_PAINT_WINDOW, TRUE,
		NULL);
	/*
	 * This line is here for backwards compatibility. It will be
	 * removed for the next release.
	 */
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

/*
 * Initialize an instance of object `display'.
 */
histo_display_objects *
histo_display_objects_initialize(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (histo_display_objects *) calloc(1, sizeof (histo_display_objects))))
		return (histo_display_objects *) NULL;
	if (!ip->display)
		ip->display = histo_display_display_create(ip, owner);
	if (!ip->controls2)
		ip->controls2 = histo_display_controls2_create(ip, ip->display);
	if (!ip->message1)
		ip->message1 = histo_display_message1_create(ip, ip->controls2);
	if (!ip->color_histo)
		ip->color_histo = histo_display_color_histo_create(ip, ip->controls2);
	if (!ip->refresh)
		ip->refresh = histo_display_refresh_create(ip, ip->controls2);
	if (!ip->message2)
		ip->message2 = histo_display_message2_create(ip, ip->controls2);
	if (!ip->magnify)
		ip->magnify = histo_display_magnify_create(ip, ip->controls2);
	if (!ip->unmagnify)
		ip->unmagnify = histo_display_unmagnify_create(ip, ip->controls2);
	if (!ip->restore)
		ip->restore = histo_display_restore_create(ip, ip->controls2);
	if (!ip->message5)
		ip->message5 = histo_display_message5_create(ip, ip->controls2);
	if (!ip->histocanv)
		ip->histocanv = histo_display_histocanv_create(ip, ip->display);
	return ip;
}

/*
 * Create object `display' in the specified instance.
 */
Xv_opaque
histo_display_display_create(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 565,
		XV_HEIGHT, 419,
		XV_LABEL, "Histogram Display",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `controls2' in the specified instance.
 */
Xv_opaque
histo_display_controls2_create(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 72,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message1' in the specified instance.
 */
Xv_opaque
histo_display_message1_create(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 32,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Pixel Value: NNN",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `color_histo' in the specified instance.
 */
Xv_opaque
histo_display_color_histo_create(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_color_opts();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 284,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Color...",
		PANEL_NOTIFY_PROC, histo_color_opts,
		NULL);
	return obj;
}

/*
 * Create object `refresh' in the specified instance.
 */
Xv_opaque
histo_display_refresh_create(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	extern void		histo_refresh_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 488,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Refresh",
		PANEL_NOTIFY_PROC, histo_refresh_proc,
		NULL);
	return obj;
}

/*
 * Create object `message2' in the specified instance.
 */
Xv_opaque
histo_display_message2_create(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 32,
		XV_Y, 28,
		PANEL_LABEL_STRING, "Pixel Count: NNN",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `magnify' in the specified instance.
 */
Xv_opaque
histo_display_magnify_create(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	extern void		mag_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 280,
		XV_Y, 40,
		PANEL_LABEL_STRING, "Magnify",
		PANEL_NOTIFY_PROC, mag_proc,
		NULL);
	return obj;
}

/*
 * Create object `unmagnify' in the specified instance.
 */
Xv_opaque
histo_display_unmagnify_create(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	extern void		unmag_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 360,
		XV_Y, 40,
		PANEL_LABEL_STRING, "Unmagnify",
		PANEL_NOTIFY_PROC, unmag_proc,
		NULL);
	return obj;
}

/*
 * Create object `restore' in the specified instance.
 */
Xv_opaque
histo_display_restore_create(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	extern void		restore_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 488,
		XV_Y, 40,
		PANEL_LABEL_STRING, "Restore",
		PANEL_NOTIFY_PROC, restore_proc,
		NULL);
	return obj;
}

/*
 * Create object `message5' in the specified instance.
 */
Xv_opaque
histo_display_message5_create(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 52,
		PANEL_LABEL_STRING, "Total Intensity: NNN",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `histocanv' in the specified instance.
 */
Xv_opaque
histo_display_histocanv_create(ip, owner)
	histo_display_objects	*ip;
	Xv_opaque	owner;
{
	extern Notify_value	histo_event_proc();
	extern void	histo_repaint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, (int)xv_get(ip->controls2, XV_Y) +
		      (int)xv_get(ip->controls2, XV_HEIGHT) + 2,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 325,
		CANVAS_REPAINT_PROC, histo_repaint_proc,
		CANVAS_X_PAINT_WINDOW, TRUE,
		NULL);
	xv_set(canvas_paint_window(obj), WIN_CONSUME_EVENTS,
		WIN_MOUSE_BUTTONS,
		LOC_MOVE,
		LOC_DRAG,
		LOC_WINENTER,
		LOC_WINEXIT,
		WIN_ASCII_EVENTS,
		WIN_LEFT_KEYS,
		WIN_RIGHT_KEYS,
		WIN_TOP_KEYS,
		NULL, NULL);
	notify_interpose_event_func(canvas_paint_window(obj),
		(Notify_func) histo_event_proc, NOTIFY_SAFE);
	/*
	 * This line is here for backwards compatibility. It will be
	 * removed for the next release.
	 */
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

