/*
 * zoom_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `zoom.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "zoom_ui.h"
#include <group.h>
#include "gen.h"
#include "genial.h"

void		zoom_resize_proc();

/*
 * Global object definitions.
 */
zoom_zmwin_objects	*Zoom_zmwin;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(argc, argv)
	int	argc;
	char	**argv;
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Zoom_zmwin = zoom_zmwin_objects_initialize(NULL, NULL);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Zoom_zmwin->zmwin);
	exit(0);
}

#endif


/*
 * Event callback function for `zmwin'.
 */
Notify_value
zoom_resize_proc(win, event, arg, type)
	Xv_window	win;
	Event		*event;
	Notify_arg	arg;
	Notify_event_type type;
{
	zoom_zmwin_objects *ip = (zoom_zmwin_objects *) xv_get(win, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "zoom: zoom_resize_proc: event %d\n", event_id(event));
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * Event callback function for `zmcanv'.
 */
Notify_value
zmcanv_event_proc(win, event, arg, type)
	Xv_window	win;
	Event		*event;
	Notify_arg	arg;
	Notify_event_type type;
{
	zoom_zmwin_objects *ip = (zoom_zmwin_objects *) xv_get(xv_get(win, CANVAS_PAINT_CANVAS_WINDOW), XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "zoom: zmcanv_event_proc: event %d\n", event_id(event));
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * Repaint callback function for `zmcanv'.
 */
void
zmcanv_repaint_proc(canvas, paint_window, display, xid, rects)
	Canvas		canvas;
	Xv_window	paint_window;
	Display		*display;
	Window		xid;
	Xv_xrectlist	*rects;
{
	fputs("zoom: zmcanv_repaint_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Event callback function for `zmwin'.
 */
Notify_value
zoom_zmwin_event_callback(win, event, arg, type)
	Xv_window	win;
	Event		*event;
	Notify_arg	arg;
	Notify_event_type type;
{
	zoom_zmwin_objects *ip = (zoom_zmwin_objects *) xv_get(win, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "zoom: zoom_zmwin_event_callback: event %d\n", event_id(event));
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (event_action(event) == WIN_RESIZE)
	{
		zoom_resize_proc(win, event, arg, type);
	}
	
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * User-defined action for `zmwin'.
 */
void
zoom_resize_proc(win, event, arg, type)
	Xv_window	win;
	Event		*event;
	Notify_arg	arg;
	Notify_event_type type;
{
	zoom_zmwin_objects *ip = (zoom_zmwin_objects *) xv_get(win, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "zoom: zoom_resize_proc: event %d\n", event_id(event));
}
