/*
 * genial.h - Contains the object declarations for project genial
 * This file was generated by `gxv'.
 */


#include "comment_ui.h"
#include "display_ui.h"
#include "file_ui.h"
#include "main_control_ui.h"
#include "gfm_ui.h"
#include "histo_ui.h"
#include "trace_ui.h"
#include "zoom_ui.h"


extern	comment_comm_win_objects	*Comment_comm_win;
extern	file_window1_objects	*File_window1;
extern	file_rect_choice_win_objects	*File_rect_choice_win;
extern	main_control_ctrlwin_objects	*Main_control_ctrlwin;
extern	main_control_imgwin_objects	*Main_control_imgwin;
extern	histo_display_objects	*Histo_display;
extern	display_ctrlwin_objects	*Display_ctrlwin;
extern	gfm_popup_objects	*Gfm_popup;
extern	histo_histo_ctrl_objects	*Histo_histo_ctrl;
extern	trace_tcntrl_objects	*Trace_tcntrl;
extern	trace_trwin_objects	*Trace_trwin;
extern	trace_intgwin_objects	*Trace_intgwin;
extern	zoom_zmwin_objects	*Zoom_zmwin;
