#ifndef	trace_HEADER
#define	trace_HEADER

/*
 * trace_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `trace.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	tcntrl;
	Xv_opaque	controls1;
	Xv_opaque	traceno;
	Xv_opaque	radius;
	Xv_opaque	scale;
	Xv_opaque	min;
	Xv_opaque	max;
} trace_tcntrl_objects;

extern trace_tcntrl_objects	*trace_tcntrl_objects_initialize();

extern Xv_opaque	trace_tcntrl_tcntrl_create();
extern Xv_opaque	trace_tcntrl_controls1_create();
extern Xv_opaque	trace_tcntrl_traceno_create();
extern Xv_opaque	trace_tcntrl_radius_create();
extern Xv_opaque	trace_tcntrl_scale_create();
extern Xv_opaque	trace_tcntrl_min_create();
extern Xv_opaque	trace_tcntrl_max_create();

typedef struct {
	Xv_opaque	trwin;
	Xv_opaque	controls2;
	Xv_opaque	mes1;
	Xv_opaque	tr_refresh;
	Xv_opaque	mes3;
	Xv_opaque	options;
	Xv_opaque	mes4;
	Xv_opaque	trcanv;
	Xv_opaque	controls3;
	Xv_opaque	integrate;
	Xv_opaque	intg_eval;
} trace_trwin_objects;

extern trace_trwin_objects	*trace_trwin_objects_initialize();

extern Xv_opaque	trace_trwin_trwin_create();
extern Xv_opaque	trace_trwin_controls2_create();
extern Xv_opaque	trace_trwin_mes1_create();
extern Xv_opaque	trace_trwin_tr_refresh_create();
extern Xv_opaque	trace_trwin_mes3_create();
extern Xv_opaque	trace_trwin_options_create();
extern Xv_opaque	trace_trwin_mes4_create();
extern Xv_opaque	trace_trwin_trcanv_create();
extern Xv_opaque	trace_trwin_controls3_create();
extern Xv_opaque	trace_trwin_integrate_create();
extern Xv_opaque	trace_trwin_intg_eval_create();

typedef struct {
	Xv_opaque	intgwin;
	Xv_opaque	controls4;
	Xv_opaque	message1;
	Xv_opaque	intgcanv;
} trace_intgwin_objects;

extern trace_intgwin_objects	*trace_intgwin_objects_initialize();

extern Xv_opaque	trace_intgwin_intgwin_create();
extern Xv_opaque	trace_intgwin_controls4_create();
extern Xv_opaque	trace_intgwin_message1_create();
extern Xv_opaque	trace_intgwin_intgcanv_create();
#endif
