#
# makefile for jpeg/man
#

MANPAGES = cjpeg.1 djpeg.1 jpegtran.1 rdjpgcom.1 wrjpgcom.1

install: man-pgm

clean:	clean-pgm

clean-all:	clean_all

man:
#	cp -p $(MANPAGES) $(MANDIR)
	$(MANPRINT) $(MANPAGES)

doc:
