#
# makefile for directory pub
#

# Subdirectories that get made

DIRS = include libman libsrc man sources

# default action just makes src dirs

all: install

clean install pristine man doc: doit
	@for d in $(DIRS) ; do \
		( cd $$d ; echo make $@ on $(HERE)$$d ; make $(MFLAGS) $@ ) ; \
	done

doit:
