#
# makefile for directory user-contributed/lbl
#

# Subdirectories that get made

DIRS = man libsrc sources

# default action just makes src dirs

all: install

clean install pristine man doc: doit
	@for d in $(DIRS) ; do \
		( cd $$d ; echo make $@ on $(HERE)$$d ; make $(MFLAGS) $@ ) ; \
	done

doit:
