/*
 * xhist_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `xhist.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/icon_load.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "xhist_ui.h"

/*
 * Initialize an instance of object `win'.
 */
xhist_win_objects *
xhist_win_objects_initialize(ip, owner)
	xhist_win_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (xhist_win_objects *) calloc(1, sizeof (xhist_win_objects))))
		return (xhist_win_objects *) NULL;
	if (!ip->win)
		ip->win = xhist_win_win_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = xhist_win_controls1_create(ip, ip->win);
	if (!ip->file_item)
		ip->file_item = xhist_win_file_item_create(ip, ip->controls1);
	if (!ip->button4)
		ip->button4 = xhist_win_button4_create(ip, ip->controls1);
	if (!ip->quit_item)
		ip->quit_item = xhist_win_quit_item_create(ip, ip->controls1);
	if (!ip->button6)
		ip->button6 = xhist_win_button6_create(ip, ip->controls1);
	if (!ip->button5)
		ip->button5 = xhist_win_button5_create(ip, ip->controls1);
	if (!ip->pixel_value)
		ip->pixel_value = xhist_win_pixel_value_create(ip, ip->controls1);
	if (!ip->button1)
		ip->button1 = xhist_win_button1_create(ip, ip->controls1);
	if (!ip->button2)
		ip->button2 = xhist_win_button2_create(ip, ip->controls1);
	if (!ip->button3)
		ip->button3 = xhist_win_button3_create(ip, ip->controls1);
	if (!ip->eval_item)
		ip->eval_item = xhist_win_eval_item_create(ip, ip->controls1);
	if (!ip->restore_item)
		ip->restore_item = xhist_win_restore_item_create(ip, ip->controls1);
	if (!ip->button7)
		ip->button7 = xhist_win_button7_create(ip, ip->controls1);
	if (!ip->count)
		ip->count = xhist_win_count_create(ip, ip->controls1);
	if (!ip->canvas)
		ip->canvas = xhist_win_canvas_create(ip, ip->win);
	return ip;
}

/*
 * Create object `win' in the specified instance.

 */
Xv_opaque
xhist_win_win_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 500,
		XV_HEIGHT, 535,
		XV_LABEL, "Display Histogram of Image",
		FRAME_CLOSED, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.

 */
Xv_opaque
xhist_win_controls1_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 120,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `file_item' in the specified instance.

 */
Xv_opaque
xhist_win_file_item_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 7,
		XV_WIDTH, 267,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "Image File : ",
		PANEL_VALUE_X, 99,
		PANEL_VALUE_Y, 7,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 22,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `button4' in the specified instance.

 */
Xv_opaque
xhist_win_button4_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		load_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 298,
		XV_Y, 7,
		XV_WIDTH, 46,
		XV_HEIGHT, 20,
		PANEL_LABEL_STRING, "Load",
		PANEL_NOTIFY_PROC, load_proc,
		NULL);
	return obj;
}

/*
 * Create object `quit_item' in the specified instance.

 */
Xv_opaque
xhist_win_quit_item_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		quit_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 367,
		XV_Y, 7,
		XV_WIDTH, 49,
		XV_HEIGHT, 20,
		PANEL_LABEL_STRING, "QUIT",
		PANEL_NOTIFY_PROC, quit_proc,
		NULL);
	return obj;
}

/*
 * Create object `button6' in the specified instance.

 */
Xv_opaque
xhist_win_button6_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		help_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 437,
		XV_Y, 7,
		XV_WIDTH, 46,
		XV_HEIGHT, 20,
		PANEL_LABEL_STRING, "Help",
		PANEL_NOTIFY_PROC, help_proc,
		NULL);
	return obj;
}

/*
 * Create object `button5' in the specified instance.

 */
Xv_opaque
xhist_win_button5_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		check_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 270,
		XV_Y, 35,
		XV_WIDTH, 126,
		XV_HEIGHT, 20,
		PANEL_LABEL_STRING, "Check pixel value",
		PANEL_NOTIFY_PROC, check_proc,
		NULL);
	return obj;
}

/*
 * Create object `pixel_value' in the specified instance.

 */
Xv_opaque
xhist_win_pixel_value_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 9,
		XV_Y, 37,
		XV_WIDTH, 240,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "pixel value : ",
		PANEL_VALUE_X, 105,
		PANEL_VALUE_Y, 37,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 18,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `button1' in the specified instance.

 */
Xv_opaque
xhist_win_button1_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		move_left_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 120,
		XV_Y, 64,
		XV_WIDTH, 42,
		XV_HEIGHT, 20,
		PANEL_LABEL_STRING, "<--",
		PANEL_NOTIFY_PROC, move_left_proc,
		NULL);
	return obj;
}

/*
 * Create object `button2' in the specified instance.

 */
Xv_opaque
xhist_win_button2_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		move_right_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 192,
		XV_Y, 64,
		XV_WIDTH, 42,
		XV_HEIGHT, 20,
		PANEL_LABEL_STRING, "-->",
		PANEL_NOTIFY_PROC, move_right_proc,
		NULL);
	return obj;
}

/*
 * Create object `button3' in the specified instance.

 */
Xv_opaque
xhist_win_button3_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		select_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 271,
		XV_Y, 64,
		XV_WIDTH, 65,
		XV_HEIGHT, 20,
		PANEL_LABEL_STRING, "Select  |",
		PANEL_NOTIFY_PROC, select_proc,
		NULL);
	return obj;
}

/*
 * Create object `eval_item' in the specified instance.

 */
Xv_opaque
xhist_win_eval_item_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		eval_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 364,
		XV_Y, 64,
		XV_WIDTH, 43,
		XV_HEIGHT, 20,
		PANEL_LABEL_STRING, "Eval",
		PANEL_NOTIFY_PROC, eval_proc,
		NULL);
	return obj;
}

/*
 * Create object `restore_item' in the specified instance.

 */
Xv_opaque
xhist_win_restore_item_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		restore_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 429,
		XV_Y, 64,
		XV_WIDTH, 63,
		XV_HEIGHT, 20,
		PANEL_LABEL_STRING, "Restore",
		PANEL_NOTIFY_PROC, restore_proc,
		NULL);
	return obj;
}

/*
 * Create object `button7' in the specified instance.

 */
Xv_opaque
xhist_win_button7_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		set_count_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 270,
		XV_Y, 95,
		XV_WIDTH, 122,
		XV_HEIGHT, 20,
		PANEL_LABEL_STRING, "Set count margin",
		PANEL_NOTIFY_PROC, set_count_proc,
		NULL);
	return obj;
}

/*
 * Create object `count' in the specified instance.

 */
Xv_opaque
xhist_win_count_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 14,
		XV_Y, 97,
		XV_WIDTH, 231,
		XV_HEIGHT, 15,
		PANEL_LABEL_STRING, "count margin : ",
		PANEL_VALUE_X, 125,
		PANEL_VALUE_Y, 97,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_DISPLAY_LENGTH, 15,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `canvas' in the specified instance.

 */
Xv_opaque
xhist_win_canvas_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern Notify_value	canvas_event_proc();
	extern void	histogram_repaint_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 120,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		CANVAS_REPAINT_PROC, histogram_repaint_proc,
		CANVAS_X_PAINT_WINDOW, TRUE,
		NULL);
	xv_set(canvas_paint_window(obj), WIN_CONSUME_EVENTS,
		WIN_MOUSE_BUTTONS,
		LOC_DRAG,
		NULL, NULL);
	notify_interpose_event_func(canvas_paint_window(obj),
		(Notify_func) canvas_event_proc, NOTIFY_SAFE);
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

