#ifndef	xhist_HEADER
#define	xhist_HEADER

/*
 * xhist_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `xhist.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	win;
	Xv_opaque	controls1;
	Xv_opaque	file_item;
	Xv_opaque	button4;
	Xv_opaque	quit_item;
	Xv_opaque	button6;
	Xv_opaque	button5;
	Xv_opaque	pixel_value;
	Xv_opaque	button1;
	Xv_opaque	button2;
	Xv_opaque	button3;
	Xv_opaque	eval_item;
	Xv_opaque	restore_item;
	Xv_opaque	button7;
	Xv_opaque	count;
	Xv_opaque	canvas;
} xhist_win_objects;

extern xhist_win_objects	*xhist_win_objects_initialize();

extern Xv_opaque	xhist_win_win_create();
extern Xv_opaque	xhist_win_controls1_create();
extern Xv_opaque	xhist_win_file_item_create();
extern Xv_opaque	xhist_win_button4_create();
extern Xv_opaque	xhist_win_quit_item_create();
extern Xv_opaque	xhist_win_button6_create();
extern Xv_opaque	xhist_win_button5_create();
extern Xv_opaque	xhist_win_pixel_value_create();
extern Xv_opaque	xhist_win_button1_create();
extern Xv_opaque	xhist_win_button2_create();
extern Xv_opaque	xhist_win_button3_create();
extern Xv_opaque	xhist_win_eval_item_create();
extern Xv_opaque	xhist_win_restore_item_create();
extern Xv_opaque	xhist_win_button7_create();
extern Xv_opaque	xhist_win_count_create();
extern Xv_opaque	xhist_win_canvas_create();
#endif
