#
# makefile for user-contributed/surrey/man
#

MANPAGES = averages.n disp_line.n dual_thresh.n histo_line.n meanie.n \
		pick_line.n polyfit_line.n

install:	man-pgm

clean:	clean-pgm

man:
	$(MANPRINT) $(MANPAGES)

doc:

pristine:	pristineman-pgm
