#
# makefile for directory drivers/XView
#

# Subdirectories to make:

DIRS = $(XVDIRS)

# default action just makes src dirs

all: install

clean install pristine man doc: doit
	@for d in $(DIRS) ; do \
		( cd $$d ; echo make $@ on $(HERE)$$d ; make $(MFLAGS) $@ ) ; \
	done

doit:
