/* xdisp global data definitions */

#include <X11/Intrinsic.h>
#include <hipl_format.h>
#include <xdisp.h>


/* X definitions */

Colormap colormap,app_colormap;
Display  *dpy;
Visual   *visual;
Window	 rws;
int	 depth;


/* Color & graphics definitions */

int ncolors = 0;
int mentries;
GC gc;
GC lgc,llgc,rgc,dgc;
XGCValues lgcv,llgcv,rgcv,dgcv;
int black_pixel,white_pixel;
XColor colors[MAXCOLOR];

pix_data_t image_pix_data;
pix_data_t sample_pix_data;
pix_data_t hist_pix_data[4];
pix_data_t colorbar_pix_data[4];

XtAppContext  app;


/* Image, data and header definitions */

struct header hdr,hdp;
int nrows;
int ncols;
int nframes;
int pixel_format;

int srows;
int scols;

int maxrows;
int maxcols;

unsigned char **images;
unsigned char **data;
unsigned char **samples;
int **hists;
int **cdfs;

Pixmap hist_pixmaps[MAXFRAME];
Pixmap cdf_pixmaps[MAXFRAME];
Pixmap image_pixmaps[MAXFRAME];

gamma_limits_t gamma_limits[4];

unsigned char *xmap[4],*ymap;

/* String data formatting definitions */

int cdconv = RECT;
int precision = 0;

/* lut extreme values control */

int extreme_type;

/* overlay RGB/CMY mode */

int cmy_state;

/* Histogram control */

int cdf_mode;

/* HIPS stuff */

Flag_Format flagfmt[] = {
			{"e",{LASTFLAG},0,
				 {
				{PTBOOLEAN,"FALSE"},
				LASTPARAMETER
				 }
			},
			{"colors",{LASTFLAG},0,
				 {
				{PTINT,"0"},
				LASTPARAMETER
				 }
			},
			{"size",{LASTFLAG},0,
				 {
				{PTINT,"500"},
				{PTINT,"500"},
				LASTPARAMETER
				 }
			},
			LASTFLAG
		};

Filename filename;
int option_e;

int types[] = {PFFLOAT,LASTTYPE};

/* LUT and cursor definitions - cursor & lut lists are defined in the
   files automatically generated by gencursors and genluts.
*/

lut_t *current_lut;
int hips_lut_exists;
char *hips_lut;
int hips_lut_n;

int ncursors;
Cursor current_cursor;

int changing_lut;

/* Frame data definitions */

int frame;

/* Overlay definitions */

int red_frame;
int green_frame;
int blue_frame;

/* Pan & zoom definitions */

float sample_rate;
pan_box_data_t pan_box_data;

/* pix caching */

int pix_cache_on;

/* Polygon definitions */

polygon_t *polygon_list = NULL;
polygon_t *current_polygon = NULL;
int defining_poly = 0;
int naming_polys = 0;
int editing_polys = 0;
int deleting_polys = 0;
int showing_polys = 1;
int in_poly_edit = 0;
poly_edit_data_t poly_edit_data;

/* default names for ask */

char def_file_name[128];
char def_poly_name[128];

/* Widget definitions */

Widget 	app_toplevel,
	app_control,
	app_sample,
	app_pcontrol,
	app_scontrol,
	app_gcontrol,
	app_ov_gcontrol,
	app_icontrol,
	app_ycontrol,
	app_fcontrol,
	app_vcontrol,
	rt,
	draw,
	sample,
	colorbar[4],
	text,
	props,
	slider_low[4],
	slider_high[4],
	hist[4],
	s_text[4],
	info,
	a_popup,
	a_caption,
	a_text,
	a_accept,
	a_cancel;
	
