/*
 * filter_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `filter.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "segal.h"


/*
 * Notify callback function for `but_apply'.
 */
void
but_apply_filter_proc(item, event)
	Panel_item	item;
	Event		*event;
{
	filter_pop_filter_objects *ip = (filter_pop_filter_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `but_close'.
 */
void
filter_pop_filter_but_close_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	filter_pop_filter_objects *ip = (filter_pop_filter_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	xv_set(Filter_pop_filter->pop_filter, XV_SHOW, FALSE, NULL);
	
	/* gxv_end_connections */

}
