/*
 * segal.h - Contains the object declarations for project segal
 * This file was generated by `gxv'.
 */


#include "file_ui.h"
#include "filter_ui.h"
#include "image_reg_ui.h"
#include "mask_grow_ui.h"
#include "mask_log_ui.h"
#include "paint_ui.h"
#include "preferences_ui.h"
#include "threshold_ui.h"
#include "view_ui.h"
#include "list_ui.h"


extern	view_win_objects	*View_win;
extern	file_pop_load_image_objects	*File_pop_load_image;
extern	file_pop_load_mask_objects	*File_pop_load_mask;
extern	file_pop_new_mask_objects	*File_pop_new_mask;
extern	filter_pop_filter_objects	*Filter_pop_filter;
extern	image_reg_pop_image_reg_objects	*Image_reg_pop_image_reg;
extern	image_reg_pop_ref_frame_objects	*Image_reg_pop_ref_frame;
extern	mask_grow_pop_mask_grow_objects	*Mask_grow_pop_mask_grow;
extern	mask_grow_pop_options_objects	*Mask_grow_pop_options;
extern	mask_log_pop_mask_log_objects	*Mask_log_pop_mask_log;
extern	paint_win_paint_objects	*Paint_win_paint;
extern	preferences_pop_preferences_display_objects	*Preferences_pop_preferences_display;
extern	mask_log_pop_options_objects	*Mask_log_pop_options;
extern	file_pop_save_as_objects	*File_pop_save_as;
extern	view_pop_timer_objects	*View_pop_timer;
extern	list_pop_list_objects	*List_pop_list;
extern	threshold_pop_threshold_objects	*Threshold_pop_threshold;
extern	paint_win_paint_objects	*Paint_win_paint;
extern	file_pop_save_image_objects	*File_pop_save_image;
extern	paint_pop_brush_objects	*Paint_pop_brush;
