# This file is generated by `guide' for project `segal.P'.
# It is to be included by the Makefile for project `segal.P'.

SOURCES.G += file.G filter.G image_reg.G list.G mask_grow.G mask_log.G paint.G preferences.G threshold.G view.G 
STUBS.G += file.G filter.G image_reg.G list.G mask_grow.G mask_log.G paint.G preferences.G threshold.G view.G 
