#ifndef	bp_HEADER
#define	bp_HEADER

/*
 * bp_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `bp.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;

extern Xv_opaque	bp_menu_init_create();
extern Xv_opaque	bp_menu_segment_create();
extern Xv_opaque	bp_menu_2D_create();
extern Xv_opaque	bp_menu_3D_create();
extern Xv_opaque	bp_menu_render_create();

typedef struct {
	Xv_opaque	win;
	Xv_opaque	controls1;
	Xv_opaque	but_init;
	Xv_opaque	but_segment;
	Xv_opaque	but_render;
	Xv_opaque	but_close;
} bp_win_objects;

extern bp_win_objects	*bp_win_objects_initialize();

extern Xv_opaque	bp_win_win_create();
extern Xv_opaque	bp_win_controls1_create();
extern Xv_opaque	bp_win_but_init_create();
extern Xv_opaque	bp_win_but_segment_create();
extern Xv_opaque	bp_win_but_render_create();
extern Xv_opaque	bp_win_but_close_create();
#endif
