#ifndef	display_control_HEADER
#define	display_control_HEADER

/*
 * display_control_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `display_control.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	win;
	Xv_opaque	controls;
	Xv_opaque	display_type;
	Xv_opaque	display_original;
	Xv_opaque	blend_type;
	Xv_opaque	mask_type;
	Xv_opaque	msg_image;
	Xv_opaque	gamma_val;
	Xv_opaque	message;
	Xv_opaque	bg_slider;
	Xv_opaque	fg_slider;
	Xv_opaque	but_close;
} display_control_win_objects;

extern display_control_win_objects	*display_control_win_objects_initialize();

extern Xv_opaque	display_control_win_win_create();
extern Xv_opaque	display_control_win_controls_create();
extern Xv_opaque	display_control_win_display_type_create();
extern Xv_opaque	display_control_win_display_original_create();
extern Xv_opaque	display_control_win_blend_type_create();
extern Xv_opaque	display_control_win_mask_type_create();
extern Xv_opaque	display_control_win_msg_image_create();
extern Xv_opaque	display_control_win_gamma_val_create();
extern Xv_opaque	display_control_win_message_create();
extern Xv_opaque	display_control_win_bg_slider_create();
extern Xv_opaque	display_control_win_fg_slider_create();
extern Xv_opaque	display_control_win_but_close_create();
#endif
