/*
 * display_control_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `display_control.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/icon_load.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "display_control_ui.h"

/*
 * Initialize an instance of object `win'.
 */
display_control_win_objects *
display_control_win_objects_initialize(ip, owner)
	display_control_win_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (display_control_win_objects *) calloc(1, sizeof (display_control_win_objects))))
		return (display_control_win_objects *) NULL;
	if (!ip->win)
		ip->win = display_control_win_win_create(ip, owner);
	if (!ip->controls)
		ip->controls = display_control_win_controls_create(ip, ip->win);
	if (!ip->display_type)
		ip->display_type = display_control_win_display_type_create(ip, ip->controls);
	if (!ip->display_original)
		ip->display_original = display_control_win_display_original_create(ip, ip->controls);
	if (!ip->blend_type)
		ip->blend_type = display_control_win_blend_type_create(ip, ip->controls);
	if (!ip->mask_type)
		ip->mask_type = display_control_win_mask_type_create(ip, ip->controls);
	if (!ip->msg_image)
		ip->msg_image = display_control_win_msg_image_create(ip, ip->controls);
	if (!ip->gamma_val)
		ip->gamma_val = display_control_win_gamma_val_create(ip, ip->controls);
	if (!ip->message)
		ip->message = display_control_win_message_create(ip, ip->controls);
	if (!ip->bg_slider)
		ip->bg_slider = display_control_win_bg_slider_create(ip, ip->controls);
	if (!ip->fg_slider)
		ip->fg_slider = display_control_win_fg_slider_create(ip, ip->controls);
	if (!ip->but_close)
		ip->but_close = display_control_win_but_close_create(ip, ip->controls);
	return ip;
}

/*
 * Create object `win' in the specified instance.

 */
Xv_opaque
display_control_win_win_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 318,
		XV_HEIGHT, 248,
		XV_LABEL, "Segal : Display Control",
		FRAME_CLOSED, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls' in the specified instance.

 */
Xv_opaque
display_control_win_controls_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `display_type' in the specified instance.

 */
Xv_opaque
display_control_win_display_type_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		change_image_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 24,
		XV_Y, 16,
		XV_WIDTH, 207,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 89,
		PANEL_VALUE_Y, 16,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Display:",
		PANEL_NOTIFY_PROC, change_image_proc,
		PANEL_CHOICE_STRINGS,
			"Image",
			"Mask",
			"Both",
			0,
		NULL);
	return obj;
}

/*
 * Create object `display_original' in the specified instance.

 */
Xv_opaque
display_control_win_display_original_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		orig_map_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 80,
		XV_Y, 44,
		XV_WIDTH, 83,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 89,
		PANEL_VALUE_Y, 44,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_NOTIFY_PROC, orig_map_proc,
		PANEL_CHOICE_STRING, 0, "Original",
		NULL);
	return obj;
}

/*
 * Create object `blend_type' in the specified instance.

 */
Xv_opaque
display_control_win_blend_type_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		blend_type_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 72,
		XV_WIDTH, 302,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 162,
		PANEL_VALUE_Y, 72,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Combination Method:",
		PANEL_NOTIFY_PROC, blend_type_proc,
		PANEL_CHOICE_STRINGS,
			"Color Blend",
			"Overlay",
			0,
		NULL);
	return obj;
}

/*
 * Create object `mask_type' in the specified instance.

 */
Xv_opaque
display_control_win_mask_type_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		mask_type_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 68,
		XV_Y, 100,
		XV_WIDTH, 177,
		XV_HEIGHT, 23,
		PANEL_VALUE_X, 161,
		PANEL_VALUE_Y, 100,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LABEL_STRING, "Mask Model:",
		PANEL_NOTIFY_PROC, mask_type_proc,
		PANEL_CHOICE_STRINGS,
			"Cut",
			"Build",
			0,
		NULL);
	return obj;
}

/*
 * Create object `msg_image' in the specified instance.

 */
Xv_opaque
display_control_win_msg_image_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 40,
		XV_Y, 124,
		XV_WIDTH, 42,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Image",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `gamma_val' in the specified instance.

 */
Xv_opaque
display_control_win_gamma_val_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		change_colormap();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 36,
		XV_Y, 140,
		XV_WIDTH, 182,
		XV_HEIGHT, 20,
		PANEL_VALUE_X, 103,
		PANEL_VALUE_Y, 140,
		PANEL_SLIDER_WIDTH, 100,
		PANEL_LABEL_STRING, "Contrast:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, FALSE,
		PANEL_SHOW_VALUE, FALSE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 100,
		PANEL_TICKS, 0,
		PANEL_NOTIFY_PROC, change_colormap,
		NULL);
	return obj;
}

/*
 * Create object `message' in the specified instance.

 */
Xv_opaque
display_control_win_message_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 40,
		XV_Y, 168,
		XV_WIDTH, 169,
		XV_HEIGHT, 13,
		PANEL_LABEL_STRING, "Opacity for image blend:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `bg_slider' in the specified instance.

 */
Xv_opaque
display_control_win_bg_slider_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		slider_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 52,
		XV_Y, 188,
		XV_WIDTH, 204,
		XV_HEIGHT, 20,
		PANEL_VALUE_X, 103,
		PANEL_VALUE_Y, 188,
		PANEL_SLIDER_WIDTH, 100,
		PANEL_LABEL_STRING, "Image:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, FALSE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 100,
		PANEL_TICKS, 0,
		PANEL_NOTIFY_PROC, slider_proc,
		NULL);
	return obj;
}

/*
 * Create object `fg_slider' in the specified instance.

 */
Xv_opaque
display_control_win_fg_slider_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern int		slider_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 56,
		XV_Y, 208,
		XV_WIDTH, 198,
		XV_HEIGHT, 20,
		PANEL_VALUE_X, 101,
		PANEL_VALUE_Y, 208,
		PANEL_SLIDER_WIDTH, 100,
		PANEL_LABEL_STRING, "Mask:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, FALSE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 100,
		PANEL_TICKS, 0,
		PANEL_NOTIFY_PROC, slider_proc,
		NULL);
	return obj;
}

/*
 * Create object `but_close' in the specified instance.

 */
Xv_opaque
display_control_win_but_close_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern void		map_display_control();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 136,
		XV_Y, 228,
		XV_WIDTH, 51,
		XV_HEIGHT, 19,
		PANEL_LABEL_STRING, "Close",
		PANEL_NOTIFY_PROC, map_display_control,
		NULL);
	return obj;
}

